<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Estudio de Caso: Calibración Termodinámica, Eléctrica y Cinética de Degradación – Tesis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./montecarlo.html" rel="next">
<link href="./fundamentos_teoricos.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b651517ce65839d647a86e2780455cfb.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e0fdce12ac1367d4b47c179a2935dd10.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-2d6d8467bf2e75a99e72accc3c25dba4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-e0fdce12ac1367d4b47c179a2935dd10.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Estudio_de_caso.html">Modelo Matemático</a></li><li class="breadcrumb-item"><a href="./Estudio_de_caso.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración Termodinámica, Eléctrica y Cinética de Degradación</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./LOGOunach.jpeg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./LOGOunach.jpeg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tesis</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/Crisperez517/VERANO-DELFIN.git" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Tesis.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Marco Teórico y Normativa</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fundamentos_teoricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentos Teóricos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Modelo Matemático</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estudio_de_caso.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración Termodinámica, Eléctrica y Cinética de Degradación</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Simulación de Equipos (Haier HBC-150)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./montecarlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metodología de Simulación Computacional y Análisis Estadístico de Riesgo</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conclusiones y Trabajo Futuro</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#sec-motivacion-contexto" id="toc-sec-motivacion-contexto" class="nav-link active" data-scroll-target="#sec-motivacion-contexto"><span class="header-section-number">3.1</span> Motivación y Contexto del Estudio</a></li>
  <li><a href="#sec-datos-cfe" id="toc-sec-datos-cfe" class="nav-link" data-scroll-target="#sec-datos-cfe"><span class="header-section-number">3.2</span> Datos Base e Histórico de Interrupciones Eléctricas</a></li>
  <li><a href="#sec-escala-espacial" id="toc-sec-escala-espacial" class="nav-link" data-scroll-target="#sec-escala-espacial"><span class="header-section-number">3.3</span> Corrección de Escala Espacial (Factor <span class="math inline">\(\kappa_{espacial}\)</span>)</a>
  <ul class="collapse">
  <li><a href="#justificación-de-la-reducción-de-escala" id="toc-justificación-de-la-reducción-de-escala" class="nav-link" data-scroll-target="#justificación-de-la-reducción-de-escala"><span class="header-section-number">3.3.1</span> Justificación de la Reducción de Escala</a></li>
  <li><a href="#la-esperanza-matemática-local" id="toc-la-esperanza-matemática-local" class="nav-link" data-scroll-target="#la-esperanza-matemática-local"><span class="header-section-number">3.3.2</span> La Esperanza Matemática Local</a></li>
  </ul></li>
  <li><a href="#sec-distribucion-temporal" id="toc-sec-distribucion-temporal" class="nav-link" data-scroll-target="#sec-distribucion-temporal"><span class="header-section-number">3.4</span> Distribución Temporal de las Fallas</a>
  <ul class="collapse">
  <li><a href="#índice-de-la-frecuencia-de-interrupción-promedio-en-número-saifi" id="toc-índice-de-la-frecuencia-de-interrupción-promedio-en-número-saifi" class="nav-link" data-scroll-target="#índice-de-la-frecuencia-de-interrupción-promedio-en-número-saifi"><span class="header-section-number">3.4.1</span> 1. Índice de la Frecuencia de Interrupción Promedio, en número (SAIFI)</a></li>
  <li><a href="#índice-de-duración-promedio-de-interrupción-en-minutos-saidi" id="toc-índice-de-duración-promedio-de-interrupción-en-minutos-saidi" class="nav-link" data-scroll-target="#índice-de-duración-promedio-de-interrupción-en-minutos-saidi"><span class="header-section-number">3.4.2</span> 2. Índice de Duración Promedio de Interrupción, en minutos (SAIDI)</a></li>
  </ul></li>
  <li><a href="#sec-ppnh" id="toc-sec-ppnh" class="nav-link" data-scroll-target="#sec-ppnh"><span class="header-section-number">3.5</span> Modelado del Proceso de Poisson No Homogéneo (PPNH)</a>
  <ul class="collapse">
  <li><a href="#calibración-mediante-la-regla-empírica-68-95-99.7" id="toc-calibración-mediante-la-regla-empírica-68-95-99.7" class="nav-link" data-scroll-target="#calibración-mediante-la-regla-empírica-68-95-99.7"><span class="header-section-number">3.5.1</span> Calibración mediante la Regla Empírica (68-95-99.7)</a></li>
  <li><a href="#sistema-de-amplitudes-cruzadas-a_1-y-a_2" id="toc-sistema-de-amplitudes-cruzadas-a_1-y-a_2" class="nav-link" data-scroll-target="#sistema-de-amplitudes-cruzadas-a_1-y-a_2"><span class="header-section-number">3.5.2</span> Sistema de Amplitudes Cruzadas (<span class="math inline">\(A_1\)</span> y <span class="math inline">\(A_2\)</span>)</a></li>
  </ul></li>
  <li><a href="#validación-del-modelo-y-análisis-de-la-anomalía-de-enero" id="toc-validación-del-modelo-y-análisis-de-la-anomalía-de-enero" class="nav-link" data-scroll-target="#validación-del-modelo-y-análisis-de-la-anomalía-de-enero"><span class="header-section-number">3.6</span> Validación del Modelo y Análisis de la Anomalía de Enero</a></li>
  <li><a href="#sec-lognormal-duracion" id="toc-sec-lognormal-duracion" class="nav-link" data-scroll-target="#sec-lognormal-duracion"><span class="header-section-number">3.7</span> Distribución Log-Normal de las Duraciones de las Fallas electrícas</a>
  <ul class="collapse">
  <li><a href="#desglose-mensual-de-horas-de-interrupción" id="toc-desglose-mensual-de-horas-de-interrupción" class="nav-link" data-scroll-target="#desglose-mensual-de-horas-de-interrupción"><span class="header-section-number">3.7.1</span> Desglose Mensual de Horas de Interrupción</a></li>
  <li><a href="#cálculo-de-medias-y-varianzas-por-temporada-climática" id="toc-cálculo-de-medias-y-varianzas-por-temporada-climática" class="nav-link" data-scroll-target="#cálculo-de-medias-y-varianzas-por-temporada-climática"><span class="header-section-number">3.7.2</span> Cálculo de Medias y Varianzas por Temporada Climática</a></li>
  <li><a href="#transformación-algebraica-a-parámetros-log-normales" id="toc-transformación-algebraica-a-parámetros-log-normales" class="nav-link" data-scroll-target="#transformación-algebraica-a-parámetros-log-normales"><span class="header-section-number">3.7.3</span> Transformación Algebraica a Parámetros Log-Normales</a></li>
  <li><a href="#visualización-de-las-densidades-de-probabilidad-pdf" id="toc-visualización-de-las-densidades-de-probabilidad-pdf" class="nav-link" data-scroll-target="#visualización-de-las-densidades-de-probabilidad-pdf"><span class="header-section-number">3.7.4</span> Visualización de las Densidades de Probabilidad (PDF)</a></li>
  </ul></li>
  <li><a href="#hasta-aqui" id="toc-hasta-aqui" class="nav-link" data-scroll-target="#hasta-aqui"><span class="header-section-number">4</span> HASTA AQUI</a>
  <ul class="collapse">
  <li><a href="#calibración-de-la-ecuación-diferencial-estocástica-ede" id="toc-calibración-de-la-ecuación-diferencial-estocástica-ede" class="nav-link" data-scroll-target="#calibración-de-la-ecuación-diferencial-estocástica-ede"><span class="header-section-number">4.1</span> Calibración de la Ecuación Diferencial Estocástica (EDE)</a>
  <ul class="collapse">
  <li><a href="#sec-regimen-1" id="toc-sec-regimen-1" class="nav-link" data-scroll-target="#sec-regimen-1"><span class="header-section-number">4.1.1</span> Régimen 1: Operación Normal (<span class="math inline">\(\alpha(t) = 1\)</span>)</a></li>
  <li><a href="#sec-regimen-2" id="toc-sec-regimen-2" class="nav-link" data-scroll-target="#sec-regimen-2"><span class="header-section-number">4.1.2</span> Régimen 2: Falla Eléctrica (<span class="math inline">\(\alpha(t) = 2\)</span>)</a></li>
  <li><a href="#perturbaciones-discretas-apertura-de-puertas-n_puertat" id="toc-perturbaciones-discretas-apertura-de-puertas-n_puertat" class="nav-link" data-scroll-target="#perturbaciones-discretas-apertura-de-puertas-n_puertat"><span class="header-section-number">4.1.3</span> Perturbaciones Discretas: Apertura de Puertas (<span class="math inline">\(N_{puerta}(t)\)</span>)</a></li>
  </ul></li>
  <li><a href="#sec-Arrhenius" id="toc-sec-Arrhenius" class="nav-link" data-scroll-target="#sec-Arrhenius"><span class="header-section-number">4.2</span> Cinética de Degradación Térmica (Ecuación de Arrhenius)</a>
  <ul class="collapse">
  <li><a href="#el-modelo-de-daño-térmico-acumulado-da" id="toc-el-modelo-de-daño-térmico-acumulado-da" class="nav-link" data-scroll-target="#el-modelo-de-daño-térmico-acumulado-da"><span class="header-section-number">4.2.1</span> El Modelo de Daño Térmico Acumulado (<span class="math inline">\(DA\)</span>)</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Estudio_de_caso.html">Modelo Matemático</a></li><li class="breadcrumb-item"><a href="./Estudio_de_caso.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración Termodinámica, Eléctrica y Cinética de Degradación</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración Termodinámica, Eléctrica y Cinética de Degradación</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-motivacion-contexto" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-motivacion-contexto"><span class="header-section-number">3.1</span> Motivación y Contexto del Estudio</h2>
<p>El presente capítulo consolida el marco teórico desarrollado previamente, trasladándolo de una formulación matemática abstracta a un escenario de aplicación altamente crítico: la red de frío para la preservación de vacunas en Tuxtla Gutiérrez, Chiapas. La elección de esta región geográfica como caso de estudio se debe a la combinación de condiciones climatológicas de calor extremo y a la vulnerabilidad de la infraestructura eléctrica local ante fenómenos meteorológicos. Bajo este entorno, los refrigeradores institucionales que resguardan los biológicos de alto valor inmunológico operan bajo condiciones de estrés continuo.</p>
<p>Para garantizar la validez y la utilidad del modelo computacional, se evitara la parametrización arbitraria de la Ecuación Diferencial Estocástica (EDE). Un modelo probabilístico con tasas de intensidad o volatilidades carentes de fundamento físico produciría trayectorias desconectadas de la realidad operativa. Por consiguiente, el objetivo central de este capítulo es la calibración rigurosa de las variables del sistema.</p>
<p>El proceso de estimación y asignación de parámetros se desarrollará en las siguientes tres fases analíticas:</p>
<ol type="1">
<li><strong>Caracterización Estocástica del Suministro Eléctrico:</strong> Mediante el análisis de datos oficiales de la Comisión Federal de Electricidad (CFE), se modelará la frecuencia y la duración de las interrupciones del servicio eléctrico. Estas estimaciones permitirán estructurar la conmutación de la cadena de Markov y los Procesos de Poisson No Homogéneos acoplados a la ecuación.</li>
<li><strong>Calibración Termodinámica del Equipo Operativo:</strong> A partir de las especificaciones técnicas y requerimientos normados por la Organización Mundial de la Salud (OMS), se deducirán analíticamente los coeficientes de reversión a la media (<span class="math inline">\(\kappa\)</span>) y las volatilidades térmicas (<span class="math inline">\(\sigma\)</span>) que dictan el enfriamiento activo y la inercia pasiva del refrigerador de estudio.</li>
<li><strong>Cinética de Degradación Biológica:</strong> Finalmente, se vinculara el comportamiento térmico dada por la EDE con la Ecuación de Arrhenius, estableciendo el marco cuantitativo necesario para evaluar la pérdida de viabilidad farmacológica que sufren las vacunas durante algun fallo.</li>
</ol>
</section>
<section id="sec-datos-cfe" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-datos-cfe"><span class="header-section-number">3.2</span> Datos Base e Histórico de Interrupciones Eléctricas</h2>
<p>El objetivo de esta fase es modelar la tasa de ocurrencia y la escala temporal de las interrupciones del suministro eléctrico en el área geográfica de Tuxtla Gutiérrez, Chiapas. Para evitar supuestos teóricos alejados de la realidad operativa de la red local, los datos de partida no se asignaron de manera arbitraria, sino que se obtuvieron a través de los registros oficiales de la Comisión Federal de Electricidad (CFE). Mediante una solicitud de información pública de transparencia dirigida a la CFE, se obtuvo el registro histórico del promedio mensual de interrupciones y su duración para el municipio de Tuxtla Gutiérrez.</p>
<p>A partir de dicha solicitud, se recabó el comportamiento histórico del municipio para el periodo comprendido entre los años 2019 y 2025. La <a href="#tbl-interrupciones-cfe" class="quarto-xref">Tabla&nbsp;<span>3.1</span></a> contiene dicha información, presentando el número de interrupciones promedio por mes y la duración promedio en horas por cada corte de energía.</p>
<div id="tbl-interrupciones-cfe" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-interrupciones-cfe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3.1: Interrupciones eléctricas en Tuxtla Gutiérrez, Chiapas (Fuente: Solicitud de Transparencia a la CFE).
</figcaption>
<div aria-describedby="tbl-interrupciones-cfe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Año</th>
<th style="text-align: center;">Número de interrupciones promedio por mes</th>
<th style="text-align: center;">Duración Promedio de las interrupciones (Horas)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">2.02</td>
</tr>
<tr class="even">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">1.73</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">2.03</td>
</tr>
<tr class="even">
<td style="text-align: center;">2022</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">2.59</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2023</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">2.23</td>
</tr>
<tr class="even">
<td style="text-align: center;">2024</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">2.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2025</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">2.02</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El análisis de la <a href="#tbl-interrupciones-cfe" class="quarto-xref">Tabla&nbsp;<span>3.1</span></a> muestra un incremento significativo en la frecuencia de fallas a partir del año 2020, estabilizándose en una franja superior a los 40 cortes mensuales. Este cambio se debe al crecimiento de la carga térmica residencial e industrial y a la saturación de los transformadores de distribución en la mancha urbana.</p>
<p>Para la calibración de la EDE en este trabajo de investigación, se selecciono el año <strong>2024</strong> como el escenario de línea base. Dicho año presenta una media mensual de <strong>43 interrupciones por mes</strong> con una duración promedio por corte de <strong>2.39 horas</strong>. Al proyectar esta tasa mensual a una tasa anual, se tiene que el número total de interrupciones al año esperadas a nivel municipal (<span class="math inline">\(N_{total}\)</span>) es:</p>
<p><span id="eq-cortes-totales"><span class="math display">\[
N_{total} = 43 \text{ cortes/mes} \times 12 \text{ meses} = 516 \text{ cortes/año}
\tag{3.1}\]</span></span></p>
</section>
<section id="sec-escala-espacial" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-escala-espacial"><span class="header-section-number">3.3</span> Corrección de Escala Espacial (Factor <span class="math inline">\(\kappa_{espacial}\)</span>)</h2>
<section id="justificación-de-la-reducción-de-escala" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="justificación-de-la-reducción-de-escala"><span class="header-section-number">3.3.1</span> Justificación de la Reducción de Escala</h3>
<p>El valor de <span class="math inline">\(516\)</span> cortes al año obtenido en la <a href="#eq-cortes-totales" class="quarto-xref">Ecuación&nbsp;<span>3.1</span></a> es un dato agregado de todo el municipio, asi que utilizar directamente este valor para un solo refrigerador implicaría asumir que el centro de almacenamiento de vacunas sufre más de un apagón diario, lo cual no es físicamente real. Este error ocurre al ignorar que un edificio está conectado a un solo nodo de la red, no a todos simultáneamente.</p>
<p>Para solucionar esto, introducimos un factor de escala espacial. De acuerdo con el Programa para el Desarrollo del Sistema Eléctrico Nacional (PRODESEN) y los diagramas de infraestructura del Centro Nacional de Control de Energía (CENACE) <span class="citation" data-cites="sener2024prodesen">(<a href="references.html#ref-sener2024prodesen" role="doc-biblioref">Secretaría de Energía 2024</a>)</span>, la mancha urbana de Tuxtla Gutiérrez está alimentada de manera sectorizada por exactamente <strong>8 subestaciones principales</strong> de distribución (Tuxtla Céntrica, Oriente, Poniente, Terán, Tuxtla Norte, Tuxtla Dos, Mactumatzá y Real del Bosque).</p>
</section>
<section id="la-esperanza-matemática-local" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="la-esperanza-matemática-local"><span class="header-section-number">3.3.2</span> La Esperanza Matemática Local</h3>
<p>Asumiendo que los cortes de energía se distribuyen de manera uniforme sobre estas subestaciones, la probabilidad <span class="math inline">\(p\)</span> de que un corte afecte a la subestación de interés (Tuxtla Norte, encargada de alimentar la zona de hospitales y laboratorios de la Colonia Maya) es <span class="math inline">\(p = 1/8\)</span>.</p>
<p>Por consiguiente, el número de cortes que tiene el centro de almacenamiento de vacunas se comporta como una variable aleatoria binomial <span class="math inline">\(N_{local} \sim \mathcal{B}(N_{total}, p)\)</span>, cuya esperanza matemática es:</p>
<p><span id="eq-esperanza-local"><span class="math display">\[
\mathbb{E}[N_{local}] = N_{total} \times p = \frac{516 \text{ cortes}}{8 \text{ subestaciones}} = 64.5 \approx 64 \text{ cortes al año}
\tag{3.2}\]</span></span></p>
<p>Al redondear la esperanza a un número entero, establecemos una base realista de <strong>64 interrupciones esperadas al año</strong> para nuestra simulación.</p>
</section>
</section>
<section id="sec-distribucion-temporal" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-distribucion-temporal"><span class="header-section-number">3.4</span> Distribución Temporal de las Fallas</h2>
<p>Las interrupciones no ocurren de manera homogénea a lo largo del año (es decir, no ocurren exactamente 5.33 cortes cada mes). La variabilidad mensual depende directamente de los factores climáticos estacionales de la región. Para no asignar los apagones de cada mes de manera aleatoria, utilizamos el comportamiento documentado en el <em>Informe Anual de la CFE 2024</em> <span class="citation" data-cites="cfe2024informe">(<a href="references.html#ref-cfe2024informe" role="doc-biblioref">Comisión Federal de Electricidad 2024</a>)</span>, específicamente en su página 82, donde se registra la evolución de los indicadores de continuidad del servicio a lo largo de los meses.</p>
<p>Para comprender la estructura de estos datos oficiales, la CFE evalúa la continuidad del suministro a través de dos indicadores internacionales de confiabilidad:</p>
<section id="índice-de-la-frecuencia-de-interrupción-promedio-en-número-saifi" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="índice-de-la-frecuencia-de-interrupción-promedio-en-número-saifi"><span class="header-section-number">3.4.1</span> 1. Índice de la Frecuencia de Interrupción Promedio, en número (SAIFI)</h3>
<p>El indicador SAIFI (<em>System Average Interruption Frequency Index</em>) contabiliza el número promedio de interrupciones sostenidas que experimenta un usuario durante un periodo determinado (generalmente un año o un mes), es decir si se tiene una red eléctrica con un total de <span class="math inline">\(N_T\)</span> usuarios atendidos. Si en un intervalo de observación ocurren <span class="math inline">\(M\)</span> eventos de interrupción, donde cada evento <span class="math inline">\(i \in \{1, 2, \dots, M\}\)</span> afecta a una cantidad de <span class="math inline">\(N_i\)</span> usuarios, el índice SAIFI se expresa formalmente como:</p>
<p><span id="eq-saifi"><span class="math display">\[
\displaystyle \text{SAIFI} = \frac{\sum_{i=1}^{M} N_i}{N_T}
\tag{3.3}\]</span></span></p>
</section>
<section id="índice-de-duración-promedio-de-interrupción-en-minutos-saidi" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="índice-de-duración-promedio-de-interrupción-en-minutos-saidi"><span class="header-section-number">3.4.2</span> 2. Índice de Duración Promedio de Interrupción, en minutos (SAIDI)</h3>
<p>El indicador SAIDI (<em>System Average Interruption Duration Index</em>) mide la duración total acumulada de las interrupciones sostenidas que experimenta el usuario promedio dentro del periodo de evaluación. Si cada evento de falla <span class="math inline">\(i\)</span> tiene una duración temporal de <span class="math inline">\(r_i\)</span> horas, el índice SAIDI se define analíticamente mediante:</p>
<p><span id="eq-saidi"><span class="math display">\[
\displaystyle \text{SAIDI} = \frac{\sum_{i=1}^{M} N_i r_i}{N_T}
\tag{3.4}\]</span></span></p>
<p>A partir de estas definiciones, la <a href="#tbl-saidi-saifi" class="quarto-xref">Tabla&nbsp;<span>3.2</span></a> presenta la evolución mensual acumulada de los indicadores SAIDI y SAIFI reportada en la página 82 del informe anual de la CFE.</p>
<div id="tbl-saidi-saifi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-saidi-saifi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3.2: Evolución mensual acumulada de los indicadores SAIDI y SAIFI (Fuente: Informe Anual CFE 2024, p.&nbsp;82).
</figcaption>
<div aria-describedby="tbl-saidi-saifi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Mes</th>
<th style="text-align: center;">SAIDI Acumulado (Horas)</th>
<th style="text-align: center;">SAIFI Acumulado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Enero</td>
<td style="text-align: center;">0.998</td>
<td style="text-align: center;">0.013</td>
</tr>
<tr class="even">
<td style="text-align: left;">Febrero</td>
<td style="text-align: center;">1.110</td>
<td style="text-align: center;">0.017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marzo</td>
<td style="text-align: center;">1.285</td>
<td style="text-align: center;">0.022</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abril</td>
<td style="text-align: center;">2.793</td>
<td style="text-align: center;">0.027</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mayo</td>
<td style="text-align: center;">4.120</td>
<td style="text-align: center;">0.037</td>
</tr>
<tr class="even">
<td style="text-align: left;">Junio</td>
<td style="text-align: center;">5.774</td>
<td style="text-align: center;">0.053</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julio</td>
<td style="text-align: center;">6.557</td>
<td style="text-align: center;">0.065</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agosto</td>
<td style="text-align: center;">7.905</td>
<td style="text-align: center;">0.080</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Septiembre</td>
<td style="text-align: center;">8.592</td>
<td style="text-align: center;">0.096</td>
</tr>
<tr class="even">
<td style="text-align: left;">Octubre</td>
<td style="text-align: center;">9.063</td>
<td style="text-align: center;">0.103</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Noviembre</td>
<td style="text-align: center;">9.314</td>
<td style="text-align: center;">0.106</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diciembre</td>
<td style="text-align: center;">10.812</td>
<td style="text-align: center;">0.113</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Dado que el informe de la CFE publica el indicador SAIFI de forma acumulada, es necesario calcular la diferencia marginal (<span class="math inline">\(\Delta\)</span>) respecto al mes anterior para obtener el peso estadístico de cada mes de forma individual:</p>
<p><span id="eq-delta-saifi"><span class="math display">\[
\Delta \text{SAIFI}_i = \text{SAIFI}_i - \text{SAIFI}_{i-1}
\tag{3.5}\]</span></span></p>
<p>Para distribuir los 64 cortes anuales calculados para la subestación local respetando esta estacionalidad, aplicamos una regla de tres simple basada en la proporcionalidad marginal. Suponiendo que el valor total del SAIFI al final del año (<span class="math inline">\(0.113\)</span>) representa el 100% de las fallas (equivalente a los 64 cortes), entonces el incremento mensual generado en cada periodo (<span class="math inline">\(\Delta \text{SAIFI}_i\)</span>) representará una fracción directamente proporcional de cortes. Expresado de forma general para cualquier mes <span class="math inline">\(i\)</span>, la asignación viene dada por:</p>
<p><span id="eq-reparto-cortes"><span class="math display">\[
\text{Cortes}_i = \left( \frac{\Delta \text{SAIFI}_i}{\text{SAIFI}_{total}} \right) \times \mathbb{E}[N_{local}]
\tag{3.6}\]</span></span></p>
<p>Sustituyendo los valores de nuestro escenario (<span class="math inline">\(\text{SAIFI}_{total} = 0.113\)</span> y <span class="math inline">\(\mathbb{E}[N_{local}] = 64\)</span>), la ecuación del modelo es:</p>
<p><span id="eq-modelo-cortes"><span class="math display">\[
\text{Cortes}_i = \left( \frac{\Delta \text{SAIFI}_i}{0.113} \right) \times 64
\tag{3.7}\]</span></span></p>
<p>Al hacer este cálculo y redondeando al entero más cercano (realizando un ajuste para conservar la suma total en 64 cortes anuales), obtenemos la distribución estacional de las fallas eléctricas presentada en la <a href="#tbl-cortes-mensuales" class="quarto-xref">Tabla&nbsp;<span>3.3</span></a>.</p>
<div id="tbl-cortes-mensuales" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cortes-mensuales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3.3: Distribución estacional de los 64 cortes calculada mediante proporcionalidad sobre el SAIFI 2024.
</figcaption>
<div aria-describedby="tbl-cortes-mensuales-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mes</th>
<th style="text-align: center;"><span class="math inline">\(\Delta\)</span> SAIFI (Mensual)</th>
<th style="text-align: center;">Cortes Exactos Calculados</th>
<th style="text-align: center;">Cortes Asignados (Redondeo)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Enero</td>
<td style="text-align: center;">0.013</td>
<td style="text-align: center;">7.36</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Febrero</td>
<td style="text-align: center;">0.004</td>
<td style="text-align: center;">2.26</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marzo</td>
<td style="text-align: center;">0.005</td>
<td style="text-align: center;">2.83</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abril</td>
<td style="text-align: center;">0.005</td>
<td style="text-align: center;">2.83</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mayo</td>
<td style="text-align: center;">0.010</td>
<td style="text-align: center;">5.66</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Junio</td>
<td style="text-align: center;">0.016</td>
<td style="text-align: center;">9.06</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julio</td>
<td style="text-align: center;">0.012</td>
<td style="text-align: center;">6.79</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agosto</td>
<td style="text-align: center;">0.015</td>
<td style="text-align: center;">8.49</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Septiembre</td>
<td style="text-align: center;">0.016</td>
<td style="text-align: center;">9.06</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Octubre</td>
<td style="text-align: center;">0.007</td>
<td style="text-align: center;">3.96</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Noviembre</td>
<td style="text-align: center;">0.003</td>
<td style="text-align: center;">1.70</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diciembre</td>
<td style="text-align: center;">0.007</td>
<td style="text-align: center;">3.96</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El análisis de la <a href="#tbl-cortes-mensuales" class="quarto-xref">Tabla&nbsp;<span>3.3</span></a> revela con claridad los dos momentos estacionales de mayor vulnerabilidad y frecuencia de cortes en el suministro eléctrico de la región. El pico más severo se registra en <strong>Junio (9 cortes)</strong>, un fenómeno ocasionado por las altas temperaturas extremas registradas en Tuxtla Gutiérrez durante la primavera-verano, las cuales provocaron una saturación en la red de distribución eléctrica debido al uso masivo y simultáneo de sistemas de aire acondicionado. El segundo periodo crítico ocurre durante <strong>Agosto y Septiembre (8 y 9 cortes respectivamente)</strong>, coincidiendo directamente con el máximo histórico de la temporada de lluvias, tormentas tropicales y huracanes en el Sureste mexicano, eventos climáticos que suelen derribar líneas de alta tensión y afectar transformadores locales. En contraste, la época invernal se consolida como el periodo de máxima estabilidad en el servicio.</p>
</section>
</section>
<section id="sec-ppnh" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-ppnh"><span class="header-section-number">3.5</span> Modelado del Proceso de Poisson No Homogéneo (PPNH)</h2>
<p>Para integrar las interrupciones eléctricas dentro de la Ecuación Diferencial Estocástica (EDE) en tiempo continuo <span class="math inline">\(t\)</span>, donde <span class="math inline">\(t \in [0, 365]\)</span> representa los días del año, utilizamos un <strong>Proceso de Poisson No Homogéneo</strong>, cuya intensidad <span class="math inline">\(\lambda(t)\)</span> varía en función del tiempo para tener en cuenta la estacionalidad climática de la región.</p>
<p>El modelo se construye mediante la suma de una tasa base de fondo y dos funciones de perturbación gaussianas no normalizadas. La elección de núcleos gaussianos permite modelar la transición gradual de las estaciones meteorológicas sin introducir discontinuidades de salto, concentrando el riesgo exactamente en los días donde el clima somete a la red a mayor estrés.</p>
<p>La función analítica propuesta para la intensidad diaria de fallas es:</p>
<p><span id="eq-lambda-teorica"><span class="math display">\[
\lambda(t) = \lambda_{base} + A_1 \exp\left(-\frac{(t - \mu_1)^2}{2\sigma_1^2}\right) + A_2 \exp\left(-\frac{(t - \mu_2)^2}{2\sigma_2^2}\right)
\tag{3.8}\]</span></span></p>
<section id="calibración-mediante-la-regla-empírica-68-95-99.7" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="calibración-mediante-la-regla-empírica-68-95-99.7"><span class="header-section-number">3.5.1</span> Calibración mediante la Regla Empírica (68-95-99.7)</h3>
<p>Para deducir la dispersión exacta de las campanas (<span class="math inline">\(\sigma_1\)</span> y <span class="math inline">\(\sigma_2\)</span>), recurrimos a la regla empírica de la distribución normal, la cual establece que el <strong>95.4% de los datos</strong> se concentra a una distancia de <span class="math inline">\(\pm 2\sigma\)</span> respecto a la media. Igualando esta amplitud (un ancho total de <span class="math inline">\(4\sigma\)</span>) a la duración física en días de cada temporada climática en Chiapas, obtenemos la siguiente calibración analítica:</p>
<ul>
<li><strong>Tasa Base (<span class="math inline">\(\lambda_{base} = 0.0667\)</span>):</strong> Representa el riesgo mínimo constante por fallas accidentales o mantenimientos de la red, independiente del clima. Se calcula a partir de los meses más estables (febrero y noviembre, con 2 cortes al mes), resultando en <span class="math inline">\(2 \text{ cortes} / 30 \text{ días} \approx 0.0667\)</span> cortes/día.</li>
<li><strong>Ola de Calor (<span class="math inline">\(\mu_1 = 152\)</span> y <span class="math inline">\(\sigma_1 = 45\)</span>):</strong> El primer pico térmico se centra a principios de junio (día 152). La temporada de calor abarca históricamente 6 meses (de marzo a agosto, <span class="math inline">\(\approx 180\)</span> días). Aplicando la regla empírica, <span class="math inline">\(4\sigma_1 = 180 \implies \sigma_1 = 45\)</span>. Elevando al cuadrado, la varianza estacional queda en <span class="math inline">\(2\sigma_1^2 = 4050\)</span>.</li>
<li><strong>Temporada de Lluvias (<span class="math inline">\(\mu_2 = 244\)</span> y <span class="math inline">\(\sigma_2 = 30\)</span>):</strong> El segundo pico se centra a inicios de septiembre (día 244), el momento más severo de tormentas. Esta temporada abarca 4 meses (julio a octubre, <span class="math inline">\(\approx 120\)</span> días). Aplicando la regla empírica, <span class="math inline">\(4\sigma_2 = 120 \implies \sigma_2 = 30\)</span>. Su varianza estacional queda en <span class="math inline">\(2\sigma_2^2 = 1800\)</span>.</li>
</ul>
</section>
<section id="sistema-de-amplitudes-cruzadas-a_1-y-a_2" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="sistema-de-amplitudes-cruzadas-a_1-y-a_2"><span class="header-section-number">3.5.2</span> Sistema de Amplitudes Cruzadas (<span class="math inline">\(A_1\)</span> y <span class="math inline">\(A_2\)</span>)</h3>
<p>Para que los picos máximos en <span class="math inline">\(t=152\)</span> y <span class="math inline">\(t=244\)</span> alcancen exactamente una intensidad de <span class="math inline">\(0.30\)</span> cortes/día (equivalente a los 9 cortes mensuales reportados empíricamente en junio y septiembre), no basta con restar la tasa base de <span class="math inline">\(0.0667\)</span>. Al estar las campanas cercanas en el tiempo, la “cola” derecha del pico de calor contribuye a la intensidad durante la temporada de lluvias, y viceversa.</p>
<p>Para obtener las amplitudes exactas (<span class="math inline">\(A_1\)</span> y <span class="math inline">\(A_2\)</span>), se resuelve el siguiente sistema de ecuaciones evaluado en los centros <span class="math inline">\(\mu_1\)</span> y <span class="math inline">\(\mu_2\)</span>:</p>
<p><span class="math display">\[
\begin{cases}
\lambda(152) = 0.0667 + A_1 (1) + A_2 \exp\left(-\frac{(152 - 244)^2}{1800}\right) = 0.30 \\
\lambda(244) = 0.0667 + A_1 \exp\left(-\frac{(244 - 152)^2}{4050}\right) + A_2 (1) = 0.30
\end{cases}
\]</span></p>
<p>Evaluando los términos exponenciales: <span class="math display">\[
\begin{cases}
A_1 + 0.009 A_2 = 0.2333 \\
0.123 A_1 + A_2 = 0.2333
\end{cases}
\]</span></p>
<p>Al resolver este sistema, obtenemos los valores de las amplitudes: <strong><span class="math inline">\(A_1 = 0.2314\)</span></strong> y <strong><span class="math inline">\(A_2 = 0.2048\)</span></strong>. Sustituyendo todos los coeficientes, la función de intensidad es:</p>
<p><span id="eq-lambda-final"><span class="math display">\[
\lambda(t) = 0.0667 + 0.2314 \exp\left(-\frac{(t - 152)^2}{4050}\right) + 0.2048 \exp\left(-\frac{(t - 244)^2}{1800}\right)
\tag{3.9}\]</span></span></p>
<div id="fig-lambda-t" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lambda-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="intensidad_lambda.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lambda-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.1: Función de intensidad diaria de fallas eléctricas <span class="math inline">\(\lambda(t)\)</span>. El área sombreada bajo la curva representa las temporadas climáticas del año: temporada de calor en naranja (días 62 a 196), canícula en púrpura (días 196 a 227), temporada de tormentas en azul (días 227 a 304) y estabilidad invernal en gris.
</figcaption>
</figure>
</div>
<p>Como se aprecia en la <a href="#fig-lambda-t" class="quarto-xref">Figura&nbsp;<span>3.1</span></a>, el área bajo la curva de la función de intensidad <span class="math inline">\(\lambda(t)\)</span> se divide en cuatro regiones climáticas fundamentales para reflejar el comportamiento térmico de Tuxtla Gutiérrez:</p>
<ul>
<li><strong>Estabilidad Invernal (Área Gris, Días <span class="math inline">\(0 \le t &lt; 62\)</span> y <span class="math inline">\(304 &lt; t \le 366\)</span>):</strong> Abarca desde el 1 de enero hasta principios de marzo, y del 1 de noviembre al 31 de diciembre. Representa el periodo de menor demanda térmica y mayor estabilidad operacional de la red eléctrica, donde la intensidad responde únicamente a la tasa base de fallas accidentales o mantenimientos de la red (<span class="math inline">\(\lambda_{base} = 0.0667\)</span>).</li>
<li><strong>Temporada de Calor y Estiaje (Área Naranja, Días <span class="math inline">\(62 \le t &lt; 196\)</span>):</strong> Comprende del 2 de marzo al 15 de julio, alcanzando su pico máximo en <span class="math inline">\(t = 152\)</span> (1 de junio). En este periodo, las temperaturas extremas provocan la saturación de los transformadores por el uso intensivo de aire acondicionado.</li>
<li><strong>La Canícula (Área Púrpura, Días <span class="math inline">\(196 \le t &lt; 227\)</span>):</strong> Abarca aproximadamente 30 días, desde el 15 de julio hasta el 15 de agosto. Corresponde a la zona de transición e intersección entre ambas campanas gaussianas. Este fenómeno meteorológico se caracteriza por una disminución temporal de las precipitaciones y un repunte del calor extremo a mitad del verano, lo que somete al sistema eléctrico a un estrés continuo antes de la llegada de las tormentas severas.</li>
<li><strong>Temporada de Tormentas y Ciclones (Área Azul, Días <span class="math inline">\(227 \le t \le 304\)</span>):</strong> Comprende del 15 de agosto al 31 de octubre, con su punto crítico centrado en <span class="math inline">\(t = 244\)</span> (1 de septiembre). Representa la máxima incidencia de precipitación y eventos meteorológicos extremos capaces de derribar líneas de alta tensión.</li>
</ul>
</section>
</section>
<section id="validación-del-modelo-y-análisis-de-la-anomalía-de-enero" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="validación-del-modelo-y-análisis-de-la-anomalía-de-enero"><span class="header-section-number">3.6</span> Validación del Modelo y Análisis de la Anomalía de Enero</h2>
<p>Por los fundamentos de los Procesos de Poisson No Homogéneos, el número esperado de cortes en cualquier intervalo <span class="math inline">\((t_1, t_2]\)</span> está determinado por la integral definida de su función de intensidad:</p>
<p><span id="eq-integral-poisson"><span class="math display">\[
\mathbb{E}[N(t_1, t_2)] = \int_{t_1}^{t_2} \lambda(t) dt
\tag{3.10}\]</span></span></p>
<p>Para validar la consistencia analítica de nuestra función <span class="math inline">\(\lambda(t)\)</span>, particionamos el año de 366 días (considerando que el <strong>año 2024 fue bisiesto</strong>, por lo que febrero aporta 29 días al dominio) en 12 subintervalos correspondientes a los días acumulados de cada mes. Al resolver numéricamente sus respectivas integrales mediante cuadratura gaussiana, contrastamos el área teórica bajo la curva contra los objetivos empíricos de la CFE:</p>
<div id="tbl-validacion-integral" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-validacion-integral-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3.4: Validación de los Valores Esperados Teóricos vs.&nbsp;Datos Empíricos de la CFE 2024.
</figcaption>
<div aria-describedby="tbl-validacion-integral-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mes</th>
<th style="text-align: center;">Intervalo de Integración <span class="math inline">\([t_{i-1}, t_i]\)</span></th>
<th style="text-align: center;">Objetivo Empírico (CFE)</th>
<th style="text-align: center;">Esperanza calculada <span class="math inline">\(\mathbb{E}[N]\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Enero</td>
<td style="text-align: center;"><span class="math inline">\([0, 31]\)</span></td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Febrero</td>
<td style="text-align: center;"><span class="math inline">\([31, 60]\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.37</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marzo</td>
<td style="text-align: center;"><span class="math inline">\([60, 91]\)</span></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3.82</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abril</td>
<td style="text-align: center;"><span class="math inline">\([91, 121]\)</span></td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mayo</td>
<td style="text-align: center;"><span class="math inline">\([121, 152]\)</span></td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8.73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Junio</td>
<td style="text-align: center;"><span class="math inline">\([152, 182]\)</span></td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">8.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julio</td>
<td style="text-align: center;"><span class="math inline">\([182, 213]\)</span></td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8.39</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agosto</td>
<td style="text-align: center;"><span class="math inline">\([213, 244]\)</span></td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Septiembre</td>
<td style="text-align: center;"><span class="math inline">\([244, 274]\)</span></td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">7.70</td>
</tr>
<tr class="even">
<td style="text-align: left;">Octubre</td>
<td style="text-align: center;"><span class="math inline">\([274, 305]\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Noviembre</td>
<td style="text-align: center;"><span class="math inline">\([305, 335]\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diciembre</td>
<td style="text-align: center;"><span class="math inline">\([335, 366]\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">2.09</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La suma acumulada de las 12 integrales arroja un total de <strong>65.90 cortes esperados</strong> a lo largo del año. Este resultado demuestra una congruencia matemática robusta frente a los 64 cortes teóricos calculados inicialmente. La diferencia de <span class="math inline">\(+2\)</span> cortes anuales funciona como un margen de seguridad metodológico, garantizando que el modelo numérico no subestime el estrés real sobre la red de frío.</p>
<p>Finalmente, es importante destacar la inexactitud observada exclusivamente en el mes de <strong>Enero</strong> (7 cortes empíricos frente a los <span class="math inline">\(2.15\)</span> esperados por la integral). Dado que enero es un periodo climatológicamente estable (sin huracanes ni olas de calor), esta desviación es originada muy probablemente por mantenimientos extraordinarios o contingencias locales impredecibles ocurridas específicamente a inicios del año 2024.</p>
</section>
<section id="sec-lognormal-duracion" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-lognormal-duracion"><span class="header-section-number">3.7</span> Distribución Log-Normal de las Duraciones de las Fallas electrícas</h2>
<p>Una vez modelada la frecuencia con la que ocurren las interrupciones eléctricas mediante el Proceso de Poisson, el siguiente componente crítico es determinar la duración exacta de cada apagón (<span class="math inline">\(D\)</span>). En teoría de probabilidad aplicada a la ingeniería de confiabilidad, el tiempo de reparación o restablecimiento de un sistema no sigue a una distribución normal estándar.</p>
<p>La duración de una falla eléctrica es una variable aleatoria continua que presenta las siguientes dos características principales:</p>
<ol type="1">
<li><strong>Dominio estrictamente positivo:</strong> El tiempo de interrupción no puede tomar valores negativos (<span class="math inline">\(D &gt; 0\)</span>).</li>
<li><strong>Asimetría positiva (Cola pesada hacia la derecha):</strong> La inmensa mayoría de las fallas locales se resuelven en pocas horas (e.g., restablecimiento de fusibles o reconexiones de subestación), pero existe una probabilidad baja de eventos atípicos severos cuya reparación demora días enteros (e.g., explosión de transformadores o colapso de torres por huracanes).</li>
</ol>
<p>Debido a que una distribución Normal clásica asignaría probabilidad a tiempos negativos y subestimaría el riesgo de cortes prolongados, la literatura establece que las duraciones de las interrupciones eléctricas se modelan mediante una <strong>Distribución Log-normal</strong>:</p>
<p><span id="eq-lognormal-def"><span class="math display">\[
D \sim \text{LogNormal}(\mu, \sigma^2)
\tag{3.11}\]</span></span></p>
<p>Para calibrar el parámetro <span class="math inline">\(\mu\)</span> (media de los logaritmos) y el parámetro <span class="math inline">\(\sigma\)</span> (desviación estándar de los logaritmos) para cada temporada, es necesario utilizar los indicadores de la CFE.</p>
<section id="desglose-mensual-de-horas-de-interrupción" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="desglose-mensual-de-horas-de-interrupción"><span class="header-section-number">3.7.1</span> Desglose Mensual de Horas de Interrupción</h3>
<p>De acuerdo con el registro histórico municipal consolidado para el año 2024, la duración promedio de un corte en Tuxtla Gutiérrez fue de <strong><span class="math inline">\(2.39\)</span> horas por corte</strong> <a href="#tbl-interrupciones-cfe" class="quarto-xref">Tabla&nbsp;<span>3.1</span></a>. Sabiendo que el factor de escala espacial redujo el riesgo de la unidad de salud a un promedio de <strong><span class="math inline">\(64\)</span> cortes al año</strong>, podemos calcular la cantidad total de tiempo que el refrigerador clínico experimentará desabasto eléctrico a lo largo de todo el año:</p>
<p><span class="math display">\[
\text{Horas Totales Anuales} = 64 \text{ cortes/año} \times 2.39 \text{ horas/corte} = 152.96 \text{ horas}
\]</span></p>
<p>Para distribuir estas <span class="math inline">\(152.96\)</span> horas a lo largo de los 12 meses del año, respetando la intensidad de daño a la infraestructura propia de cada época del año, utilizamos el indicador de duración acumulada SAIDI del <em>Informe Anual de la CFE 2024</em> <a href="#tbl-saidi-saifi" class="quarto-xref">Tabla&nbsp;<span>3.2</span></a>.</p>
<p>El primer paso consiste en calcular la diferencia marginal (<span class="math inline">\(\Delta \text{SAIDI}_i = \text{SAIDI}_i - \text{SAIDI}_{i-1}\)</span>) para obtener el peso de cada mes individual. Posteriormente, aplicamos una <strong>regla de 3 simple</strong>: asumiendo que el valor total del SAIDI acumulado total (<span class="math inline">\(10.812\)</span> horas) representa el 100% de la afectación anual (equivalente a nuestras <span class="math inline">\(152.96\)</span> horas proyectadas), entonces el incremento de cualquier mes <span class="math inline">\(i\)</span> representará una fracción directamente proporcional de horas de corte para el centro de almacenamiento. Analíticamente, la ecuación de asignación es:</p>
<p><span class="math display">\[
\text{Horas del Mes}_i = \left( \frac{\Delta \text{SAIDI}_i}{\text{SAIDI}_{total}} \right) \times \text{Horas Totales Anuales}
\]</span></p>
<p>Sustituyendo los valores de nuestro escenario (<span class="math inline">\(\text{SAIDI}_{total} = 10.812\)</span> y <span class="math inline">\(\text{Horas Totales} = 152.96\)</span>), el modelo de asignación mensual queda como:</p>
<p><span class="math display">\[
\text{Horas del Mes}_i = \left( \frac{\Delta \text{SAIDI}_i}{10.812} \right) \times 152.96
\]</span></p>
<p>Finalmente, para conocer la duración media esperada de un corte individual en un mes específico (<span class="math inline">\(E_i\)</span>), se divide el número de horas asignadas a dicho mes entre la cantidad de cortes de ese mes calculados previamente en la <a href="#tbl-cortes-mensuales" class="quarto-xref">Tabla&nbsp;<span>3.3</span></a>. Es decir, <span class="math inline">\(E_i = \text{Horas del Mes}_i / \text{Cortes}_i\)</span>. Al hacer estos cálculos se obtienen los siguientes resultados:</p>
<div id="tbl-duracion-cortes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-duracion-cortes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3.5: Estimación de la duración promedio mensual por corte a partir de los indicadores SAIDI 2024.
</figcaption>
<div aria-describedby="tbl-duracion-cortes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Mes</th>
<th style="text-align: center;">SAIDI Acumulado</th>
<th style="text-align: center;"><span class="math inline">\(\Delta\)</span> SAIDI</th>
<th style="text-align: center;">Duración Acumulada de las Interrupciones en el Mes</th>
<th style="text-align: center;">Cortes del Mes</th>
<th style="text-align: center;">Duración Promedio <span class="math inline">\(E_i\)</span> (Horas)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Enero</td>
<td style="text-align: center;">0.998</td>
<td style="text-align: center;">0.998</td>
<td style="text-align: center;">14.12</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2.017</td>
</tr>
<tr class="even">
<td style="text-align: left;">Febrero</td>
<td style="text-align: center;">1.110</td>
<td style="text-align: center;">0.112</td>
<td style="text-align: center;">1.58</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.790</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marzo</td>
<td style="text-align: center;">1.285</td>
<td style="text-align: center;">0.175</td>
<td style="text-align: center;">2.48</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.827</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abril</td>
<td style="text-align: center;">2.793</td>
<td style="text-align: center;">1.508</td>
<td style="text-align: center;">21.33</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7.110</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mayo</td>
<td style="text-align: center;">4.120</td>
<td style="text-align: center;">1.327</td>
<td style="text-align: center;">18.77</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">3.128</td>
</tr>
<tr class="even">
<td style="text-align: left;">Junio</td>
<td style="text-align: center;">5.774</td>
<td style="text-align: center;">1.654</td>
<td style="text-align: center;">23.40</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">2.600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Julio</td>
<td style="text-align: center;">6.557</td>
<td style="text-align: center;">0.783</td>
<td style="text-align: center;">11.08</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1.583</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agosto</td>
<td style="text-align: center;">7.905</td>
<td style="text-align: center;">1.348</td>
<td style="text-align: center;">19.07</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">2.384</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Septiembre</td>
<td style="text-align: center;">8.592</td>
<td style="text-align: center;">0.687</td>
<td style="text-align: center;">9.72</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1.080</td>
</tr>
<tr class="even">
<td style="text-align: left;">Octubre</td>
<td style="text-align: center;">9.063</td>
<td style="text-align: center;">0.471</td>
<td style="text-align: center;">6.66</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1.665</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Noviembre</td>
<td style="text-align: center;">9.314</td>
<td style="text-align: center;">0.251</td>
<td style="text-align: center;">3.55</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1.775</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diciembre</td>
<td style="text-align: center;">10.812</td>
<td style="text-align: center;">1.498</td>
<td style="text-align: center;">21.19</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5.298</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="cálculo-de-medias-y-varianzas-por-temporada-climática" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="cálculo-de-medias-y-varianzas-por-temporada-climática"><span class="header-section-number">3.7.2</span> Cálculo de Medias y Varianzas por Temporada Climática</h3>
<p>Para integrar con precisión la duración de los cortes dentro de los regímenes estacionales de la EDE, es necesario agrupar los datos mensuales de la <a href="#tbl-duracion-cortes" class="quarto-xref">Tabla&nbsp;<span>3.5</span></a> en las tres temporadas climáticas previamente delimitadas en el análisis del Proceso de Poisson. La conformación dichos grupos se debe a las siguientes razones termodinámicas:</p>
<ol type="1">
<li><strong>Temporada de Calor (Abril a Julio):</strong> Agrupa el periodo de máximo estiaje y temperaturas extremas, culminando en la canícula. Durante este cuatrimestre, la saturación térmica de los equipos de distribución eléctrica es máxima.</li>
<li><strong>Temporada de Lluvias (Agosto a Octubre):</strong> Concentra el periodo crítico de huracanes y tormentas, caracterizado por daños mecánicos sobre la red eléctrica.</li>
<li><strong>Estabilidad Invernal (Enero a Marzo, Noviembre y Diciembre):</strong> Meses de baja exigencia térmica ambiental, donde los apagones ocurren mayoritariamente a factores de mantenimiento.</li>
</ol>
<p>Realizar un promedio aritmético simple de las duraciones <span class="math inline">\(E_i\)</span> entre los meses de cada temporada introduciría un sesgo grave, ya que asignaría el mismo peso a un mes con 9 cortes que a uno con solo 2 cortes. Para garantizar la rigurosidad estadística, se calcula la media empírica (<span class="math inline">\(\mathbb{E}[D]\)</span>) y la varianza empírica (<span class="math inline">\(\mathbb{V}[D]\)</span>) mediante un modelo de <strong>estadística descriptiva ponderada</strong>, donde el peso de cada mes (<span class="math inline">\(\omega_i\)</span>) está dado por su frecuencia de cortes (<span class="math inline">\(\omega_i = \text{Cortes}_i\)</span>).</p>
<p>Asi, las formulaciones para la esperanza y la varianza ponderada están dadas por:</p>
<p><span id="eq-media-ponderada"><span class="math display">\[
\mathbb{E}[D] = \frac{\sum_{i=1}^{n} \omega_i E_i}{\sum_{i=1}^{n} \omega_i} = \frac{\text{Horas Acumuladas de la Temporada}}{\text{Cortes Totales de la Temporada}}
\tag{3.12}\]</span></span></p>
<p><span id="eq-varianza-ponderada"><span class="math display">\[
\mathbb{V}[D] = \frac{\sum_{i=1}^{n} \omega_i (E_i - \mathbb{E}[D])^2}{\sum_{i=1}^{n} \omega_i}
\tag{3.13}\]</span></span></p>
<p>Al sustituir los valores de los meses correspondientes en las <a href="#eq-media-ponderada" class="quarto-xref">Ecuación&nbsp;<span>3.12</span></a> y <a href="#eq-varianza-ponderada" class="quarto-xref">Ecuación&nbsp;<span>3.13</span></a>, se obtienen los siguientes resultados para cada temporada:</p>
<ul>
<li><strong>Temporada de Calor (Abr, May, Jun, Jul):</strong> Acumula un total de <span class="math inline">\(25\)</span> cortes y <span class="math inline">\(74.58\)</span> horas de interrupción, arrojando una duración media alta de <span class="math inline">\(\mathbb{E}[D] = 2.983\)</span> horas y una varianza considerable de <span class="math inline">\(\mathbb{V}[D] = 2.651\)</span>, esto se debe a las anomalías de colapso de red registradas durante las olas de calor primaverales.</li>
<li><strong>Temporada de Lluvias (Ago, Sep, Oct):</strong> Acumula <span class="math inline">\(21\)</span> cortes pero únicamente <span class="math inline">\(35.45\)</span> horas de interrupción. Esto nos da una media notablemente más baja de <span class="math inline">\(\mathbb{E}[D] = 1.688\)</span> horas y una varianza muy estable de <span class="math inline">\(\mathbb{V}[D] = 0.343\)</span>, indicando que las fallas por lluvia son frecuentes pero suelen ser restablecidas con rapidez.</li>
<li><strong>Estabilidad Invernal (Ene, Feb, Mar, Nov, Dic):</strong> Acumula <span class="math inline">\(18\)</span> cortes y <span class="math inline">\(42.92\)</span> horas de interrupción. Su duración media es de <span class="math inline">\(\mathbb{E}[D] = 2.384\)</span> horas con una varianza alta de <span class="math inline">\(\mathbb{V}[D] = 2.667\)</span>, provocada por mantenimientos atípicos observados en los bordes del año (especialmente en enero y diciembre).</li>
</ul>
</section>
<section id="transformación-algebraica-a-parámetros-log-normales" class="level3" data-number="3.7.3">
<h3 data-number="3.7.3" class="anchored" data-anchor-id="transformación-algebraica-a-parámetros-log-normales"><span class="header-section-number">3.7.3</span> Transformación Algebraica a Parámetros Log-Normales</h3>
<p>Una vez conocidas las medias (<span class="math inline">\(\mathbb{E}[D]\)</span>) y varianzas (<span class="math inline">\(\mathbb{V}[D]\)</span>), estas deben transformarse hacia los parámetros <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> que conforman la función de distribución Log-normal.</p>
<p>La teoría de la probabilidad nos dice que la esperanza y la varianza de una variable con distribución Log-normal dependen de sus parámetros a través del siguiente sistema de ecuaciones no lineales:</p>
<p><span class="math display">\[
\mathbb{E}[D] = \exp\left(\mu + \frac{\sigma^2}{2}\right)
\]</span> <span class="math display">\[
\mathbb{V}[D] = \left[\exp(\sigma^2) - 1\right] \exp(2\mu + \sigma^2)
\]</span></p>
<p>Sustituyendo la primera ecuación en la segunda, la varianza puede reescribirse como <span class="math inline">\(\mathbb{V}[D] = (\mathbb{E}[D])^2 \left[\exp(\sigma^2) - 1\right]\)</span>. A partir de esta simplificación, se despeja el sistema para obtener las fórmulas inversas de calibración:</p>
<p><span id="eq-sigma-lognormal"><span class="math display">\[
\sigma = \sqrt{\ln\left(1 + \frac{\mathbb{V}[D]}{(\mathbb{E}[D])^2}\right)}
\tag{3.14}\]</span></span></p>
<p><span id="eq-mu-lognormal"><span class="math display">\[
\mu = \ln(\mathbb{E}[D]) - \frac{\sigma^2}{2} = \ln\left( \frac{(\mathbb{E}[D])^2}{\sqrt{\mathbb{V}[D] + (\mathbb{E}[D])^2}} \right)
\tag{3.15}\]</span></span></p>
<p>Al sustituir las medias y varianzas empíricas de cada temporada en las ecuaciones anteriores, obtenemos los parámetros exactos de la distribución Log-normal que modelará la duración de las fallas eléctricas en cada temporada:</p>
<div id="tbl-parametros-lognormal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-parametros-lognormal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3.6: Parámetros finales de la distribución Log-normal por temporada climática.
</figcaption>
<div aria-describedby="tbl-parametros-lognormal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Temporada Climática</th>
<th style="text-align: center;">Meses que integran lo Integran</th>
<th style="text-align: center;">Media Ponderada <span class="math inline">\(\mathbb{E}[D]\)</span></th>
<th style="text-align: center;">Varianza Ponderada <span class="math inline">\(\mathbb{V}[D]\)</span></th>
<th style="text-align: center;">Parámetro <span class="math inline">\(\mu\)</span></th>
<th style="text-align: center;">Parámetro <span class="math inline">\(\sigma\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Estabilidad (Invierno)</strong></td>
<td style="text-align: center;">Ene, Feb, Mar, Nov, Dic</td>
<td style="text-align: center;">2.384</td>
<td style="text-align: center;">2.667</td>
<td style="text-align: center;">0.6766</td>
<td style="text-align: center;">0.6202</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Calor (Estiaje y Canícula)</strong></td>
<td style="text-align: center;">Abr, May, Jun, Jul</td>
<td style="text-align: center;">2.983</td>
<td style="text-align: center;">2.651</td>
<td style="text-align: center;">0.9627</td>
<td style="text-align: center;">0.5106</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Lluvias (Tormentas)</strong></td>
<td style="text-align: center;">Ago, Sep, Oct</td>
<td style="text-align: center;">1.688</td>
<td style="text-align: center;">0.343</td>
<td style="text-align: center;">0.4668</td>
<td style="text-align: center;">0.3372</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="visualización-de-las-densidades-de-probabilidad-pdf" class="level3" data-number="3.7.4">
<h3 data-number="3.7.4" class="anchored" data-anchor-id="visualización-de-las-densidades-de-probabilidad-pdf"><span class="header-section-number">3.7.4</span> Visualización de las Densidades de Probabilidad (PDF)</h3>
<p>Para comprender físicamente el comportamiento de los apagones en cada época del año, es fundamental analizar la Función de Densidad de Probabilidad (PDF, por sus siglas en inglés) de las tres distribuciones calibradas anteriormente. Matemáticamente, la función de densidad para una variable aleatoria <span class="math inline">\(D\)</span> con distribución Log-normal se define como:</p>
<p><span id="eq-pdf-lognormal"><span class="math display">\[
f(x; \mu, \sigma) = \frac{1}{x \sigma \sqrt{2\pi}} \exp\left( - \frac{(\ln x - \mu)^2}{2\sigma^2} \right), \quad \text{para } x &gt; 0
\tag{3.16}\]</span></span></p>
<p>Donde <span class="math inline">\(x\)</span> representa la duración del corte eléctrico en horas, y el área bajo la curva en un intervalo <span class="math inline">\([a, b]\)</span> representa la probabilidad exacta de que un apagón dure entre <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> horas.</p>
<p>A continuación, se grafican las densidades de probabilidad para cada temporada climática, utilizando los parámetros <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> deducidos en la <a href="#tbl-parametros-lognormal" class="quarto-xref">Tabla&nbsp;<span>3.6</span></a>. Para facilitar la comparación visual del riesgo, todas las gráficas se evalúan en una ventana de observación de 0 a 12 horas.</p>
<div id="fig-lognormal-invierno" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lognormal-invierno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lognormal_invierno.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lognormal-invierno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.2: Función de densidad de probabilidad Log-normal para la Temporada de Estabilidad (Invierno). Su distribución muestra una dispersión considerable (<span class="math inline">\(\sigma = 0.6202\)</span>), lo que refleja una mezcla de cortes breves y mantenimientos atípicos prolongados.
</figcaption>
</figure>
</div>
<div id="fig-lognormal-calor" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lognormal-calor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lognormal_calor.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lognormal-calor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.3: Función de densidad de probabilidad Log-normal para la Temporada de Calor. Presenta el mayor desplazamiento hacia la derecha (<span class="math inline">\(\mu = 0.9627\)</span>) y una “cola pesada”, advirtiendo que los cortes por saturación térmica de transformadores tienen una alta probabilidad de prolongarse por varias horas, representando el mayor peligro para la red de frío.
</figcaption>
</figure>
</div>
<div id="fig-lognormal-lluvias" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lognormal-lluvias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="lognormal_lluvias.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lognormal-lluvias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.4: Función de densidad de probabilidad Log-normal para la Temporada de Tormentas (Lluvias). Exhibe un pico muy pronunciado al inicio y una cola corta (<span class="math inline">\(\sigma = 0.3371\)</span>), lo que indica que, aunque los cortes por lluvia son frecuentes, la CFE logra restablecer el servicio rápidamente en la gran mayoría de los casos.
</figcaption>
</figure>
</div>
<p>El análisis de estas tres distribuciones valida teóricamente la hipótesis de vulnerabilidad térmica de la investigación: el verdadero riesgo para la viabilidad de las vacunas no radica en la cantidad de cortes durante la época de huracanes, ya que estos suelen ser breves, sino en la pesada cola derecha de la distribución de la Temporada de Calor, donde los apagones prolongados coinciden con las temperaturas ambientales más agresivas del año.</p>
</section>
</section>
<section id="hasta-aqui" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> HASTA AQUI</h1>
<section id="calibración-de-la-ecuación-diferencial-estocástica-ede" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="calibración-de-la-ecuación-diferencial-estocástica-ede"><span class="header-section-number">4.1</span> Calibración de la Ecuación Diferencial Estocástica (EDE)</h2>
<p>Enlazando la dinámica de la red eléctrica con la termodinámica, recordamos que la temperatura interna <span class="math inline">\(T(t)\)</span> del refrigerador está gobernada por un proceso de Ornstein-Uhlenbeck con saltos y conmutación de régimen. Para que la transición hacia el modelo computacional sea transparente, desglosamos la ecuación abstracta en su forma operativa mediante un sistema de ecuaciones acopladas, el cual depende estrictamente del estado del suministro eléctrico <span class="math inline">\(\alpha(t)\)</span>:</p>
<p><span id="eq-ede-operativa"><span class="math display">\[
dT(t) =
\begin{cases}
\kappa_{on}(\theta_{set} - T(t))dt + \sigma_{on}dW(t) + \gamma dN_{puerta}(t) &amp; \text{si } \alpha(t) = 1 \text{ (Con energía)} \\
\kappa_{off}(T_{amb}(t) - T(t))dt + \sigma_{off}dW(t) + \gamma dN_{puerta}(t) &amp; \text{si } \alpha(t) = 2 \text{ (Corte de luz)}
\end{cases}
\tag{4.1}\]</span></span></p>
<p>Para la modelación estocástica, los parámetros de inercia térmica y tiempo de autonomía (<em>holdover time</em>) se calibraron utilizando los datos técnicos del refrigerador institucional Haier HBC-150, el cual cuenta con certificación de protección Grado A contra congelamiento en el catálogo oficial PQS de la OMS <span class="citation" data-cites="oms_pqs_e003">(<a href="references.html#ref-oms_pqs_e003" role="doc-biblioref">Organización Mundial de la Salud 2024</a>)</span>.</p>
<div id="fig-haier-hbc150" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-haier-hbc150-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="haier_hbc150.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-haier-hbc150-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.1: Refrigerador institucional para vacunas Haier HBC-150 (Icelined Refrigerator). Este equipo tipo cofre cuenta con certificación PQS de la OMS y masa térmica incorporada para garantizar la red de frío durante cortes prolongados de energía eléctrica.
</figcaption>
</figure>
</div>
<p>Para reflejar el comportamiento de este equipo bajo los rigurosos estándares normativos, calibramos cada coeficiente de la <a href="#eq-ede-operativa" class="quarto-xref">Ecuación&nbsp;<span>4.1</span></a> con base en la física del enfriamiento:</p>
<section id="sec-regimen-1" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="sec-regimen-1"><span class="header-section-number">4.1.1</span> Régimen 1: Operación Normal (<span class="math inline">\(\alpha(t) = 1\)</span>)</h3>
<p>Ocurre cuando hay energía eléctrica y el compresor funciona empujando la temperatura hacia su objetivo.</p>
<ul>
<li><strong>Temperatura de Consigna (<span class="math inline">\(\theta_{set}\)</span>)</strong>: Se establece en <strong><span class="math inline">\(4^\circ \text{C}\)</span></strong>, el centro ideal del rango normativo de seguridad (2°C a 8°C).</li>
<li><strong>Velocidad de Enfriamiento (<span class="math inline">\(\kappa_{on}\)</span>)</strong>: Representa la capacidad de potencia del motor para recuperar la temperatura. Se calibra en <span class="math inline">\(\kappa_{on} = 0.1188\)</span>, una velocidad rápida propia de la compresión activa de acuerdo con <span class="citation" data-cites="oms_pqs_e003">(<a href="references.html#ref-oms_pqs_e003" role="doc-biblioref">Organización Mundial de la Salud 2024</a>)</span>.</li>
<li><strong>Ruido del Compresor (<span class="math inline">\(\sigma_{on}\)</span>)</strong>: El motor se prende y se apaga constantemente para mantener los 4°C. Acorde con un intervalo de confianza del 99.7% (aplicando la regla de las 3 sigmas de la distribución normal), queremos que las fluctuaciones máximas no excedan los <span class="math inline">\(\pm 2^\circ \text{C}\)</span> para evitar llegar a los 2°C (riesgo de congelación) o a los 6°C. Sabiendo que <span class="math inline">\(3 \times SD = 2^\circ \text{C}\)</span>, la desviación estándar estacionaria debe ser <span class="math inline">\(SD \approx 0.667^\circ \text{C}\)</span>. Despejando la volatilidad de la varianza a largo plazo del proceso Ornstein-Uhlenbeck <span class="math inline">\(\left(SD = \frac{\sigma_{on}}{\sqrt{2\kappa_{on}}}\right)\)</span>: <span class="math display">\[0.667 = \frac{\sigma_{on}}{\sqrt{2(0.1188)}} \implies \sigma_{on} \approx 0.325\]</span></li>
</ul>
</section>
<section id="sec-regimen-2" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="sec-regimen-2"><span class="header-section-number">4.1.2</span> Régimen 2: Falla Eléctrica (<span class="math inline">\(\alpha(t) = 2\)</span>)</h3>
<p>Se activa cuando el Proceso de Poisson dice que hay un apagón y el enfriamiento activo se detiene.</p>
<ul>
<li><strong>Temperatura Exterior (<span class="math inline">\(T_{amb}(t)\)</span>)</strong>: La temperatura ambiente actúa como el atractor del sistema. Dado que en Tuxtla Gutiérrez el calor oscila drásticamente a lo largo del día, esta variable se modela computacionalmente como una función senoidal que alcanza su pico máximo a las 15:00 hrs. Para nuestra calibración analítica del peor escenario (estiaje), evaluamos este atractor en un máximo absoluto de <strong><span class="math inline">\(43^\circ \text{C}\)</span></strong>. En este escenario, el término <span class="math inline">\((T_{amb} - T(t))\)</span> se vuelve enorme y genera un calentamiento fuertemente acelerado.</li>
<li><strong>Velocidad de Pérdida Térmica (<span class="math inline">\(\kappa_{off}\)</span>)</strong>: De acuerdo con las especificaciones del fabricante validadas por la OMS <span class="citation" data-cites="oms_pqs_e003">(<a href="references.html#ref-oms_pqs_e003" role="doc-biblioref">Organización Mundial de la Salud 2024</a>)</span>, el equipo Haier HBC-150 garantiza un <em>Holdover Time</em> (tiempo de autonomía) de 60 horas con 50 minutos (60.83 horas) a una temperatura ambiente extrema de 43°C antes de rebasar los 8°C. Usando la solución analítica determinista de la Ley de Enfriamiento de Newton desde los 4°C de consigna hasta el límite de 8°C: <span class="math display">\[8 = 43 + (4 - 43) e^{-\kappa_{off} (60.83)}\]</span> Al resolver la ecuación <span class="math inline">\(\left(\ln\left(\frac{35}{39}\right) = -60.83 \kappa_{off}\right)\)</span>, obtenemos un valor sumamente bajo de <span class="math inline">\(\kappa_{off} \approx 0.00178 \text{ hr}^{-1}\)</span>. Esta dramática diferencia entre un parámetro rápido (<span class="math inline">\(\kappa_{on}\)</span>) y uno muy lento (<span class="math inline">\(\kappa_{off}\)</span>) demuestra la efectividad de los revestimientos de hielo y justifica el uso de EDEs con conmutación de régimen.</li>
<li><strong>Volatilidad Externa (<span class="math inline">\(\sigma_{off}\)</span>)</strong>: Sin el compresor encendido, las variaciones aleatorias obedecen únicamente a micro-filtraciones de aire por las gomas de la puerta. Por ello, establecemos un ruido significativamente menor: <span class="math inline">\(\sigma_{off} = 0.05\)</span>.</li>
</ul>
</section>
<section id="perturbaciones-discretas-apertura-de-puertas-n_puertat" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="perturbaciones-discretas-apertura-de-puertas-n_puertat"><span class="header-section-number">4.1.3</span> Perturbaciones Discretas: Apertura de Puertas (<span class="math inline">\(N_{puerta}(t)\)</span>)</h3>
<p>De acuerdo con las normativas internacionales de manejo de red de frío, el refrigerador debe abrirse idealmente un máximo de dos veces al día: una apertura rutinaria matutina para extraer los frascos necesarios para la jornada y una vespertina para resguardar los sobrantes.</p>
<ul>
<li><strong>Tasa de Aperturas (<span class="math inline">\(\lambda_{puerta}\)</span>)</strong>: Dado que la apertura matutina es un evento operativo fijo, la verdadera estocasticidad recae en la tarde, ya que el ingreso de biológicos depende de si hubo sobrantes en los termos clínicos. Por ello, la perturbación aleatoria se restringe a este momento y se modela computacionalmente con un Proceso de Poisson Homogéneo con una tasa de <span class="math inline">\(\lambda = 1\)</span> evento/día.</li>
<li><strong>Impacto de la Apertura (<span class="math inline">\(\gamma\)</span>)</strong>: Al tratarse de un equipo tipo cofre (<em>Icelined Refrigerator</em>), la pérdida térmica es mucho menor que en equipos verticales, ya que el aire frío, siendo más denso, tiende a permanecer en el fondo del gabinete. Sin embargo, basándonos en estudios de convección para una apertura prolongada típica de 5 minutos (tiempo estimado para organizar y contabilizar viales), se introduce una carga térmica inesperada. Asignamos un incremento de <strong><span class="math inline">\(\gamma = +1^\circ \text{C}\)</span></strong> por evento. Esta es una perturbación instantánea que rompe la continuidad de la trayectoria y reduce críticamente el “colchón térmico” disponible en caso de ocurrir un apagón durante la noche.</li>
</ul>
</section>
</section>
<section id="sec-Arrhenius" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-Arrhenius"><span class="header-section-number">4.2</span> Cinética de Degradación Térmica (Ecuación de Arrhenius)</h2>
<p>La Ecuación Diferencial Estocástica calibrada anteriormente nos permite simular con alta precisión la temperatura interna del refrigerador <span class="math inline">\(T(t)\)</span>. Sin embargo, para evaluar el impacto en la salud pública, es necesario traducir estas variaciones térmicas en pérdida de viabilidad del biológico.</p>
<p>La degradación de las vacunas (particularmente las vivas atenuadas, como el biológico contra el Sarampión o la Poliomielitis) es un proceso de desnaturalización proteica que se acelera exponencialmente con el calor. Esta velocidad de degradación <span class="math inline">\(k(T)\)</span> se modela mediante la <strong>Ecuación de Arrhenius</strong> <span class="citation" data-cites="chen2009thermostable">(<a href="references.html#ref-chen2009thermostable" role="doc-biblioref">Chen y Kristensen 2009</a>)</span>:</p>
<p><span id="eq-Arrhenius"><span class="math display">\[
k(T(t)) = A \exp\left(-\frac{E_a}{R \cdot T_K(t)}\right)
\tag{4.2}\]</span></span></p>
<p>Donde la temperatura <span class="math inline">\(T_K(t) = T(t) + 273.15\)</span> se expresa en grados Kelvin y los parámetros cinéticos para un biológico termosensible genérico se establecen como:</p>
<ul>
<li><strong>Constante Universal de los Gases (<span class="math inline">\(R\)</span>)</strong>: <span class="math inline">\(8.314 \, \text{J/(mol} \cdot \text{K)}\)</span>.</li>
<li><strong>Energía de Activación (<span class="math inline">\(E_a\)</span>)</strong>: Se calibra en <strong><span class="math inline">\(85,000 \, \text{J/mol}\)</span></strong> (<span class="math inline">\(85 \text{ kJ/mol}\)</span>). Este valor representa la barrera energética que debe superarse para que las proteínas del antígeno comiencen a romperse irreversiblemente.</li>
<li><strong>Factor Pre-exponencial (<span class="math inline">\(A\)</span>)</strong>: Se ajusta a un valor de <strong><span class="math inline">\(1.2 \times 10^{14}\)</span></strong>. Este factor de frecuencia asegura que la tasa de degradación sea prácticamente nula cuando el equipo opera correctamente en el rango normativo de 2°C a 8°C, pero escale logarítmicamente durante una excursión térmica severa.</li>
</ul>
<section id="el-modelo-de-daño-térmico-acumulado-da" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="el-modelo-de-daño-térmico-acumulado-da"><span class="header-section-number">4.2.1</span> El Modelo de Daño Térmico Acumulado (<span class="math inline">\(DA\)</span>)</h3>
<p>En la práctica clínica normativa, las variaciones térmicas dentro del rango seguro (2°C a 8°C) se consideran tolerables y su impacto en la caducidad a corto plazo es ignorado. El daño crítico ocurre exclusivamente cuando la red de frío se rompe.</p>
<p>Para modelar este protocolo operativo dentro de nuestra simulación, el <strong>Daño Acumulado (<span class="math inline">\(DA\)</span>)</strong> se calcula como la integral de la tasa de Arrhenius, condicionada por una función indicadora <span class="math inline">\(\mathbb{I}_{\{T(t) &gt; 8^\circ\text{C}\}}\)</span> que “enciende” el reloj de degradación únicamente cuando la temperatura cruza el límite superior de seguridad:</p>
<p><span class="math display">\[
DA(t) = \int_{0}^{t} \mathbb{I}_{\{T(s) &gt; 8\}} \cdot k(T(s)) \, ds
\]</span></p>
<p>Esta formulación integral permite que el simulador de Montecarlo contabilice el estrés térmico exacto de cada trayectoria. Si durante un apagón prolongado la EDE empuja a <span class="math inline">\(T(t)\)</span> muy por encima de los 8°C, el integrando crecerá rápidamente. Si al final de un año simulado el <span class="math inline">\(DA(t)\)</span> rebasa un umbral de descarte crítico predefinido, el lote de vacunas se considerará como pérdida total.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-chen2009thermostable" class="csl-entry" role="listitem">
Chen, Dexiang, y Debra Kristensen. 2009. <span>«Opportunities and challenges of developing thermostable vaccines»</span>. <em>Expert review of vaccines</em> 8 (5): 547-57. <a href="https://doi.org/10.1586/erv.09.20">https://doi.org/10.1586/erv.09.20</a>.
</div>
<div id="ref-cfe2024informe" class="csl-entry" role="listitem">
Comisión Federal de Electricidad. 2024. <span>«Informe Anual 2024»</span>. Ciudad de México: Gobierno de México.
</div>
<div id="ref-oms_pqs_e003" class="csl-entry" role="listitem">
Organización Mundial de la Salud. 2024. <em>WHO Immunisation Devices - Performance, Quality &amp; Safety. E003: Refrigerators and freezers</em>. World Health Organization. <a href="https://apps.who.int/immunization_standards/vaccine_quality/pqs_catalogue/index.aspx">https://apps.who.int/immunization_standards/vaccine_quality/pqs_catalogue/index.aspx</a>.
</div>
<div id="ref-sener2024prodesen" class="csl-entry" role="listitem">
Secretaría de Energía. 2024. <span>«Programa para el Desarrollo del Sistema Eléctrico Nacional (PRODESEN) 2024-2038»</span>. Ciudad de México: Gobierno de México.
</div>
</div>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./fundamentos_teoricos.html" class="pagination-link" aria-label="Fundamentos Teóricos">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentos Teóricos</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./montecarlo.html" class="pagination-link" aria-label="Metodología de Simulación Computacional y Análisis Estadístico de Riesgo">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metodología de Simulación Computacional y Análisis Estadístico de Riesgo</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>