<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Simulación Computacional y Análisis de Resultados – Tesis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./conclusiones.html" rel="next">
<link href="./Estudio_de_caso.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b651517ce65839d647a86e2780455cfb.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e0fdce12ac1367d4b47c179a2935dd10.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-2d6d8467bf2e75a99e72accc3c25dba4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-e0fdce12ac1367d4b47c179a2935dd10.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./montecarlo.html">Simulación de Equipos (Haier HBC-150)</a></li><li class="breadcrumb-item"><a href="./montecarlo.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simulación Computacional y Análisis de Resultados</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./LOGOunach.jpeg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./LOGOunach.jpeg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tesis</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/Crisperez517/VERANO-DELFIN.git" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Tesis.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Marco Teórico y Normativa</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fundamentos_teoricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentos Teóricos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Modelo Matemático</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Estudio_de_caso.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración Termodinámica, Eléctrica y Cinética de Degradación</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Simulación de Equipos (Haier HBC-150)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./montecarlo.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simulación Computacional y Análisis de Resultados</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conclusiones y Trabajo Futuro</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#malla-temporal-y-clima-exterior" id="toc-malla-temporal-y-clima-exterior" class="nav-link active" data-scroll-target="#malla-temporal-y-clima-exterior"><span class="header-section-number">4.1</span> Malla Temporal y Clima Exterior</a></li>
  <li><a href="#sec-parametrizacion-fisica" id="toc-sec-parametrizacion-fisica" class="nav-link" data-scroll-target="#sec-parametrizacion-fisica"><span class="header-section-number">4.2</span> Parametrización Física, Cinética y Estocástica</a>
  <ul class="collapse">
  <li><a href="#sec-params-termo" id="toc-sec-params-termo" class="nav-link" data-scroll-target="#sec-params-termo"><span class="header-section-number">4.2.1</span> Parámetros Termodinámicos y Biológicos</a></li>
  <li><a href="#sec-aperturas-puerta" id="toc-sec-aperturas-puerta" class="nav-link" data-scroll-target="#sec-aperturas-puerta"><span class="header-section-number">4.2.2</span> Apertura de Puertas (<span class="math inline">\(N_{puerta}(t)\)</span>)</a></li>
  <li><a href="#sec-riesgo-cfe" id="toc-sec-riesgo-cfe" class="nav-link" data-scroll-target="#sec-riesgo-cfe"><span class="header-section-number">4.2.3</span> Riesgo Eléctrico de la CFE</a></li>
  </ul></li>
  <li><a href="#precalibración-vectorizada-de-eventos-externos" id="toc-precalibración-vectorizada-de-eventos-externos" class="nav-link" data-scroll-target="#precalibración-vectorizada-de-eventos-externos"><span class="header-section-number">4.3</span> Precalibración Vectorizada de Eventos Externos</a></li>
  <li><a href="#resolución-numérica-de-la-ecuación-diferencial-estocástica-ede" id="toc-resolución-numérica-de-la-ecuación-diferencial-estocástica-ede" class="nav-link" data-scroll-target="#resolución-numérica-de-la-ecuación-diferencial-estocástica-ede"><span class="header-section-number">4.4</span> Resolución Numérica de la Ecuación Diferencial Estocástica (EDE)</a>
  <ul class="collapse">
  <li><a href="#integración-numérica-por-cambios-de-régimen" id="toc-integración-numérica-por-cambios-de-régimen" class="nav-link" data-scroll-target="#integración-numérica-por-cambios-de-régimen"><span class="header-section-number">4.4.1</span> Integración Numérica por Cambios de Régimen</a></li>
  <li><a href="#sec-resultados-seguridad" id="toc-sec-resultados-seguridad" class="nav-link" data-scroll-target="#sec-resultados-seguridad"><span class="header-section-number">4.4.2</span> Resultados de Seguridad Termodinámica</a></li>
  <li><a href="#análisis-comparativo-de-trayectorias-visión-macro-anual" id="toc-análisis-comparativo-de-trayectorias-visión-macro-anual" class="nav-link" data-scroll-target="#análisis-comparativo-de-trayectorias-visión-macro-anual"><span class="header-section-number">4.4.3</span> Análisis Comparativo de Trayectorias: Visión Macro (Anual)</a></li>
  <li><a href="#análisis-comparativo-de-trayectorias-visión-micro-acercamiento-mensual" id="toc-análisis-comparativo-de-trayectorias-visión-micro-acercamiento-mensual" class="nav-link" data-scroll-target="#análisis-comparativo-de-trayectorias-visión-micro-acercamiento-mensual"><span class="header-section-number">4.4.4</span> Análisis Comparativo de Trayectorias: Visión Micro (Acercamiento Mensual)</a></li>
  </ul></li>
  <li><a href="#integración-de-la-dinámica-logística-y-mermas" id="toc-integración-de-la-dinámica-logística-y-mermas" class="nav-link" data-scroll-target="#integración-de-la-dinámica-logística-y-mermas"><span class="header-section-number">4.5</span> Integración de la Dinámica Logística y Mermas</a>
  <ul class="collapse">
  <li><a href="#resultados-del-impacto-logístico" id="toc-resultados-del-impacto-logístico" class="nav-link" data-scroll-target="#resultados-del-impacto-logístico"><span class="header-section-number">4.5.1</span> Resultados del Impacto Logístico</a></li>
  <li><a href="#análisis-comparativo-del-inventario-y-riesgo-materializado" id="toc-análisis-comparativo-del-inventario-y-riesgo-materializado" class="nav-link" data-scroll-target="#análisis-comparativo-del-inventario-y-riesgo-materializado"><span class="header-section-number">4.5.2</span> Análisis Comparativo del Inventario y Riesgo Materializado</a></li>
  </ul></li>
  <li><a href="#estructura-de-la-simulación-de-montecarlo" id="toc-estructura-de-la-simulación-de-montecarlo" class="nav-link" data-scroll-target="#estructura-de-la-simulación-de-montecarlo"><span class="header-section-number">4.6</span> Estructura de la Simulación de Montecarlo</a></li>
  <li><a href="#resultados-estadísticos-y-análisis-de-riesgo" id="toc-resultados-estadísticos-y-análisis-de-riesgo" class="nav-link" data-scroll-target="#resultados-estadísticos-y-análisis-de-riesgo"><span class="header-section-number">4.7</span> Resultados Estadísticos y Análisis de Riesgo</a>
  <ul class="collapse">
  <li><a href="#riesgo-operativo-y-termodinámico-empírico" id="toc-riesgo-operativo-y-termodinámico-empírico" class="nav-link" data-scroll-target="#riesgo-operativo-y-termodinámico-empírico"><span class="header-section-number">4.7.1</span> Riesgo Operativo y Termodinámico Empírico</a></li>
  <li><a href="#análisis-de-trayectorias" id="toc-análisis-de-trayectorias" class="nav-link" data-scroll-target="#análisis-de-trayectorias"><span class="header-section-number">4.7.2</span> Análisis de Trayectorias</a></li>
  <li><a href="#estacionalidad-del-riesgo-operativo" id="toc-estacionalidad-del-riesgo-operativo" class="nav-link" data-scroll-target="#estacionalidad-del-riesgo-operativo"><span class="header-section-number">4.7.3</span> Estacionalidad del Riesgo Operativo</a></li>
  </ul></li>
  <li><a href="#de-aqui" id="toc-de-aqui" class="nav-link" data-scroll-target="#de-aqui"><span class="header-section-number">5</span> DE AQUI</a>
  <ul class="collapse">
  <li><a href="#distribución-del-riesgo-operativo" id="toc-distribución-del-riesgo-operativo" class="nav-link" data-scroll-target="#distribución-del-riesgo-operativo"><span class="header-section-number">5.0.1</span> Distribución del Riesgo Operativo</a></li>
  </ul></li>
  <li><a href="#hasta-aqui" id="toc-hasta-aqui" class="nav-link" data-scroll-target="#hasta-aqui"><span class="header-section-number">6</span> HASTA AQUI</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./montecarlo.html">Simulación de Equipos (Haier HBC-150)</a></li><li class="breadcrumb-item"><a href="./montecarlo.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simulación Computacional y Análisis de Resultados</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simulación Computacional y Análisis de Resultados</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Para evaluar la confiabilidad de la red de frío frente a la volatilidad del suministro eléctrico y las condiciones climáticas de Tuxtla Gutiérrez, Chiapas, desarrollamos una simulación en Python enfocado en el equipo institucional Haier HBC-150 presentado en la sección anterior. Debido a la interacción simultánea de múltiples procesos aleatorios (cortes de energía, aperturas de puerta, inercia térmica y consumo logístico), el sistema no posee una solución analítica cerrada. En consecuencia, recurrimos a la integración numérica de trayectorias acoplada al método de Montecarlo.</p>
<p>A diferencia de modelos estáticos tradicionales, esta investigación evalúa el riesgo bajo tres contextos operativos distintos para medir el impacto de la interacción humana:</p>
<ul>
<li><strong>Escenario A (Línea Base):</strong> Control absoluto sin interacción operativa. Aísla el riesgo provocado exclusivamente por el clima exterior y las fallas de la red eléctrica.</li>
<li><strong>Escenario B (Apego Normativo):</strong> Consumo y aperturas bajo los lineamientos estándar recomendados.</li>
<li><strong>Escenario C (Contingencia):</strong> Estrés operativo severo, modelando alta rotación del inventario y resurtidos aleatorios mediante procesos de Poisson.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Nota sobre Reproducibilidad:</strong> Con el fin de mantener este documento con un formato limpio y legible, hemos omitido el código fuente de programación en el texto. Los algoritmos completos para cada escenario se encuentran documentados detalladamente en el repositorio público de GitHub de este proyecto <span class="citation" data-cites="Perez2026EscenarioA Perez2026EscenarioB Perez2026EscenarioC">(<a href="references.html#ref-Perez2026EscenarioA" role="doc-biblioref">Pérez, C. 2026a</a>, <a href="references.html#ref-Perez2026EscenarioB" role="doc-biblioref">2026b</a>, <a href="references.html#ref-Perez2026EscenarioC" role="doc-biblioref">2026c</a>)</span>.</p>
</blockquote>
<p>A continuación, explicamos la metodología de la simulación, la estructuración del código y los supuestos físicos considerados (como la inercia térmica del biológico). Posteriormente, presentamos el análisis estadístico y la discusión de los resultados obtenidos para cada escenario.</p>
<section id="malla-temporal-y-clima-exterior" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="malla-temporal-y-clima-exterior"><span class="header-section-number">4.1</span> Malla Temporal y Clima Exterior</h2>
<p>El primer módulo de la simulación establece el tiempo y el clima de Tuxtla Gutiérrez. Creamos una malla de tiempo para cubrir un año bisiesto completo de 366 días. Para capturar los cambios rápidos en la temperatura interna del refrigerador, elegimos un paso de integración discreto de exactamente 5 minutos (<span class="math inline">\(\Delta t = 5/60\)</span> horas). Esto genera un total de 105,408 iteraciones por cada año simulado.</p>
<p>Para sincronizar el modelo con la logística institucional, programamos un calendario interno que identifica los días hábiles (lunes a viernes) y excluye tanto los fines de semana (sábados y domingos) como los días festivos oficiales. De esta manera, garantizamos que la extracción operativa de vacunas ocurra exclusivamente durante las jornadas laborales reales.</p>
<p>En cuanto al entorno climático, cargamos una base de datos meteorológica real de la ciudad. Sin embargo, los registros públicos solo proveen la temperatura promedio diaria (<span class="math inline">\(T_{media}\)</span>), lo cual oculta el verdadero estrés térmico que ocurre a lo largo del día. Para solucionar esto, expandimos el dato diario a nuestra escala de 5 minutos utilizando una función senoidal. Calibramos esta función con una amplitud de <strong>7°C</strong>, lo que equivale a una variación típica de <strong>14°C</strong> entre el frío de la madrugada y el calor máximo de la tarde de Tuxtla Gutiérrez. Además, ajustamos la ecuación para forzar que el pico máximo de la temperatura golpee exactamente a las 15:00 horas de cada día simulado:</p>
<p><span class="math display">\[T_{amb}(t) = T_{media}(t) + 7.0 \cdot \cos\left(2\pi \frac{t - 15}{24}\right)\]</span></p>
<p>Donde <span class="math inline">\(t\)</span> representa el tiempo en horas, es decir, <span class="math inline">\(t \in [0, 8784)\)</span> para un año completo de 366 días.</p>
<p>El resultado de esta oscilación se observa en la <a href="#fig-clima-anual" class="quarto-xref">Figura&nbsp;<span>4.1</span></a>, que muestra el comportamiento térmico para todo el año, y en la <a href="#fig-clima-zoom" class="quarto-xref">Figura&nbsp;<span>4.2</span></a>, que demuestra la consistencia del ciclo diurno. Es importante destacar que, dado que el clima de la ciudad es un factor independiente, estas condiciones ambientales y gráficas aplican de manera idéntica para los tres escenarios evaluados (A, B y C).</p>
<div id="fig-clima-anual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clima-anual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="temp_anual_tuxtla_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clima-anual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.1: Temperatura ambiente continua simulada para Tuxtla Gutiérrez a lo largo de un año, comparada con los promedios diarios de la base meteorológica.
</figcaption>
</figure>
</div>
<div id="fig-clima-zoom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clima-zoom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="temp_zoom_tuxtla_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clima-zoom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.2: Acercamiento a un periodo de 5 días de simulación climática (Mayo), donde se observa el ciclo senoidal y los picos térmicos a las 15:00 horas.
</figcaption>
</figure>
</div>
</section>
<section id="sec-parametrizacion-fisica" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-parametrizacion-fisica"><span class="header-section-number">4.2</span> Parametrización Física, Cinética y Estocástica</h2>
<p>Una vez construido el entorno climático, inicializamos las constantes que controlan la termodinámica del equipo institucional Haier HBC-150 y las propiedades fisicoquímicas de las vacunas.</p>
<section id="sec-params-termo" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="sec-params-termo"><span class="header-section-number">4.2.1</span> Parámetros Termodinámicos y Biológicos</h3>
<p>Asignamos los coeficientes térmicos estimados para la Ecuación Diferencial Estocástica (EDE) de Orstein Uhlenbeck. Alineados a las normativas vigentes, el termostato y la temperatura inicial del equipo se establecen en <span class="math inline">\(\theta = 5.0^\circ\text{C}\)</span> y <span class="math inline">\(T_0 = 5.0^\circ\text{C}\)</span>. Cuando el equipo tiene suministro eléctrico, la tasa de abatimiento térmico es de <span class="math inline">\(\kappa_{on} = 0.1154\,\text{hr}^{-1}\)</span>, con una volatilidad interna debido a los ventiladores de <span class="math inline">\(\sigma_{on} = 0.4804\)</span>, calculados en la <a href="Estudio_de_caso.html#sec-regimen-1" class="quarto-xref"><span>Sección 3.9.1</span></a>.</p>
<p>Ante una falla eléctrica, el compresor se apaga. El aislamiento de alta densidad del equipo frena la transferencia de calor exterior con una inercia pasiva de <span class="math inline">\(\kappa_{off} = 0.00232\,\text{hr}^{-1}\)</span> y un ruido por microfiltraciones de <span class="math inline">\(\sigma_{off} = 0.048\)</span>, estimado en la <a href="Estudio_de_caso.html#sec-regimen-2" class="quarto-xref"><span>Sección 3.9.2</span></a>.</p>
<p>Para modelar la degradación biológica, utilizamos la ecuación de Arrhenius (<a href="Estudio_de_caso.html#eq-Arrhenius" class="quarto-xref">Ecuación&nbsp;<span>3.19</span></a>) calibrada para un biológico termosensible representativo. La energía de activación se fija en <span class="math inline">\(E_a = 85,000\,\text{J/mol}\)</span>, la constante de los gases en <span class="math inline">\(R = 8.314\,\text{J/(mol}\cdot\text{K)}\)</span> y el factor preexponencial en <span class="math inline">\(A = 1.2 \times 10^{13} \, \text{s}^{-1}\)</span> (obtenidos en la <a href="Estudio_de_caso.html#sec-Arrhenius" class="quarto-xref"><span>Sección 3.10</span></a>). Adicionalmente, fundamentados en la termodinámica de fluidos, introducimos un <strong>filtro de inercia térmica de 30 minutos</strong>; es decir, asumimos que el biológico líquido dentro del frasco de vidrio tarda este periodo en igualar la temperatura interna del equipo, evitando contabilizar falsos daños por picos térmicos breves.</p>
</section>
<section id="sec-aperturas-puerta" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="sec-aperturas-puerta"><span class="header-section-number">4.2.2</span> Apertura de Puertas (<span class="math inline">\(N_{puerta}(t)\)</span>)</h3>
<p>La interacción humana se modela extrayendo vacunas únicamente durante las jornadas laborales (lunes a viernes). Para evaluar el impacto logístico, la simulación adapta estas perturbaciones dependiendo del contexto operativo (como se vio en la <a href="Estudio_de_caso.html#sec-perturbaciones-discretas" class="quarto-xref"><span>Sección 3.9.3</span></a>), los tres escenarios de prueba se definen de la siguiente manera:</p>
<ul>
<li><strong>Escenario A (Línea Base):</strong> No existe interacción humana; la tasa de aperturas es estrictamente cero durante todo el año.</li>
<li><strong>Escenario B (Apego Normativo):</strong> Se programa una apertura determinista a las 8:00 AM para la extracción de dosis diarias. Posteriormente, se activa un proceso de Poisson con intensidad <span class="math inline">\(\lambda_{tarde} = 0.5 \text{ eventos/hora}\)</span>$ en un horario vespertino de 2 horas (de 15:00 a 17:00 hrs) para las aperturas aleatorias vespertinas de resguardo.</li>
<li><strong>Escenario C (Contingencia):</strong> Además de la extracción matutina y vespertina del Escenario B, se usa otro proceso de Poisson de alta frecuencia (<span class="math inline">\(\lambda_{resurtido} = 0.4 \text{ eventos/hora}\)</span>) en un horario matutino de 5 horas (de 09:00 a 14:00 hrs) para simular viajes masivos de abastecimiento debido a la saturación del inventario.</li>
</ul>
<p>Como se analizó en la <a href="Estudio_de_caso.html#sec-salto-termico" class="quarto-xref"><span>Sección 3.9.4</span></a>, cada apertura inyecta aire caliente al interior del equipo. Este impacto se calcula mediante un salto térmico aleatorio <span class="math inline">\(\gamma_i\)</span>, extraído de una distribución Normal truncada (<a href="Estudio_de_caso.html#eq-salto-termico" class="quarto-xref">Ecuación&nbsp;<span>3.18</span></a>) para reflejar la variabilidad real en el tiempo que la puerta permanece abierta.</p>
</section>
<section id="sec-riesgo-cfe" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="sec-riesgo-cfe"><span class="header-section-number">4.2.3</span> Riesgo Eléctrico de la CFE</h3>
<p>El riesgo del suministro eléctrico se parametriza utilizando el comportamiento histórico de la Comisión Federal de Electricidad (CFE). Retomando los cálculos de la <a href="Estudio_de_caso.html#sec-ppnh" class="quarto-xref"><span>Sección 3.5</span></a>, programamos la tasa de fallas diarias <span class="math inline">\(\lambda_{cfe}(t)\)</span> para el Proceso de Poisson No Homogéneo. Este modelo promedia un aproximado de 64 cortes anuales, combinando un riesgo base constante con dos campanas estacionales que simulan el sobrecalentamiento de transformadores en primavera y la temporada de tormentas en verano:</p>
<p><span class="math display">\[
\lambda_{cfe}(t) = 0.0667 + 0.2314 \cdot \exp\left(-\frac{(t - 152)^2}{4050}\right) + 0.2048 \cdot \exp\left(-\frac{(t - 244)^2}{1800}\right)
\]</span></p>
<p>Para la duración de estos cortes, utilizamos una distribución Log-Normal calibrada por el método de los momentos en la <a href="Estudio_de_caso.html#sec-lognormal-duracion" class="quarto-xref"><span>Sección 3.7</span></a> para las distintas épocas del año:</p>
<ul>
<li><strong>Temporada Base:</strong> <span class="math inline">\(\mu = 0.6766, \ \sigma = 0.6202\)</span></li>
<li><strong>Temporada de Calor:</strong> <span class="math inline">\(\mu = 0.9627, \ \sigma = 0.5106\)</span></li>
<li><strong>Temporada de Lluvias:</strong> <span class="math inline">\(\mu = 0.4668, \ \sigma = 0.3372\)</span></li>
</ul>
</section>
</section>
<section id="precalibración-vectorizada-de-eventos-externos" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="precalibración-vectorizada-de-eventos-externos"><span class="header-section-number">4.3</span> Precalibración Vectorizada de Eventos Externos</h2>
<p>Antes de resolver numéricamente la Ecuación Diferencial Estocástica para la temperatura, el algoritmo ejecuta un módulo de precalculo vectorizado para optimizar los tiempos de ejecución. En esta fase, el programa simula de manera independiente las variables externas que afectarán al equipo institucional a lo largo del año.</p>
<p>Para el suministro eléctrico, el algoritmo recorre secuencialmente los 366 días del año. En cada jornada, consulta la intensidad estacional de la CFE y realiza un muestreo aleatorio de Poisson para determinar cuántas fallas eléctricas ocurrirán. Si el resultado es mayor a cero, selecciona una hora de inicio distribuida de manera uniforme entre las 0 y las 24 horas del día, y realiza un muestreo Log-Normal condicionado a la época del año para determinar la duración del corte. Con estos datos, el algoritmo modifica el vector de estado eléctrico <span class="math inline">\(S(t)\)</span>, cambiando su valor de 1 (con energía) a 0 (falla eléctrica) durante el intervalo afectado.</p>
<p>Por otro lado, para modelar las aperturas de la puerta del equipo, se genera un vector binario de eventos evaluado en el dominio de tiempo discreto <span class="math inline">\(t \in \{0, \Delta t, 2\Delta t, \dots, 8784\}\)</span> horas. Dado que el paso de integración se fijó en <span class="math inline">\(\Delta t = 5/60\)</span> horas (5 minutos), este conjunto se particiona exactamente en 105,408 iteraciones para cubrir la totalidad del año. Este vector se construye de manera dinámica dependiendo del modelo evaluado: se mantiene nulo para el Escenario A, combina las aperturas matutinas fijas con la probabilidad vespertina (<span class="math inline">\(\lambda_{tarde} \cdot \Delta t\)</span>) para el Escenario B, y adiciona la perturbación logística de resurtidos (<span class="math inline">\(\lambda_{resurtido} \cdot \Delta t\)</span>) para el Escenario C.</p>
<p>Posteriormente, el algoritmo aplica una regla estricta de control operativo: multiplica el vector de aperturas por la función de estado eléctrico <span class="math inline">\(S(t)\)</span>, evaluada en el mismo dominio de <span class="math inline">\([0, 8784]\)</span> horas. Esto garantiza que si el centro de almacenamiento de vacunas se encuentra bajo un apagón en un instante específico (<span class="math inline">\(S(t)=0\)</span>), la probabilidad de apertura en ese mismo instante de tiempo <span class="math inline">\(t\)</span> se reduce a cero de forma absoluta. Esto refleja el protocolo normativo real que prohíbe abrir el equipo sin energía eléctrica para evitar la pérdida acelerada de frío.</p>
<p>Finalmente, los eventos validos de apertura de la puerta del equipo se sustituyen por su respectiva magnitud de impacto térmico (<span class="math inline">\(\gamma_i\)</span>), el cual es extraído de una distribución Normal truncada (<a href="Estudio_de_caso.html#eq-salto-termico" class="quarto-xref">Ecuación&nbsp;<span>3.18</span></a>), finalizando así el vector discreto de saltos térmicos (<span class="math inline">\(Saltos\_Termicos(t)\)</span>).</p>
<p>Para validar la correcta precalibración del entorno, ejecutamos una trayectoria anual de prueba fijando una semilla de control (<code>np.random.seed(42)</code>). La simulación generó una trayectoria eléctrica idéntica para los tres casos con un total de <strong>68 apagones</strong> en el año, en dónde hubo una notoria diferencia fue en el vector de saltos térmicos: el personal registró <strong>0 aperturas</strong> para el Escenario A (Línea Base), <strong>493 aperturas</strong> para el Escenario B (Apego Normativo), y <strong>995 aperturas</strong> debido a la saturación logística en el Escenario C (Contingencia).</p>
</section>
<section id="resolución-numérica-de-la-ecuación-diferencial-estocástica-ede" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="resolución-numérica-de-la-ecuación-diferencial-estocástica-ede"><span class="header-section-number">4.4</span> Resolución Numérica de la Ecuación Diferencial Estocástica (EDE)</h2>
<p>Con los vectores de perturbaciones externas precalculados, el algoritmo ejecuta la resolución de la evolución de la temperatura interna del equipo y extrae las métricas de seguridad termodinámica para el equipo institucional.</p>
<section id="integración-numérica-por-cambios-de-régimen" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="integración-numérica-por-cambios-de-régimen"><span class="header-section-number">4.4.1</span> Integración Numérica por Cambios de Régimen</h3>
<p>Para avanzar en el tiempo, el algoritmo recorre cada iteración <span class="math inline">\(i \in [1, 105407]\)</span>. El índice arranca en 1 porque el primer valor corresponde a la condición inicial térmica del equipo (<span class="math inline">\(T_0 = 5.0^\circ\text{C}\)</span>). En cada paso, se evalúa el estado del suministro eléctrico previo (<span class="math inline">\(S_{t}[i-1]\)</span>), activando un cambio de régimen dinámico (<em>regime-switching</em>):</p>
<ul>
<li>Si el suministro está activo (<span class="math inline">\(S=1\)</span>), se aplican los parámetros de convección forzada (<span class="math inline">\(\kappa_{on}, \sigma_{on}\)</span>), llevando la temperatura hacia el objetivo del termostato (<span class="math inline">\(\theta = 5.0^\circ\text{C}\)</span>) y sumando el salto térmico <span class="math inline">\(\gamma_i\)</span> si la puerta fue manipulada.</li>
<li>Si el suministro presenta una falla (<span class="math inline">\(S=0\)</span>), se aplican los parámetros de inercia térmica pasiva (<span class="math inline">\(\kappa_{off}, \sigma_{off}\)</span>), provocando que la temperatura interna sea atraída lentamente hacia la temperatura ambiente exterior de Tuxtla Gutiérrez (<span class="math inline">\(T_{amb}[i-1]\)</span>).</li>
</ul>
<p>La solución numérica se ejecuta mediante el esquema de Euler-Maruyama desarrollado en la <a href="fundamentos_teoricos.html#sec-euler-maruyama" class="quarto-xref"><span>Sección 2.7.1</span></a>. Es importante destacar que, dado que las volatilidades térmicas (<span class="math inline">\(\sigma_{on}\)</span> y <span class="math inline">\(\sigma_{off}\)</span>) actúan como ruidos aditivos constantes (independientes del estado de la temperatura <span class="math inline">\(T(t)\)</span>), sus derivadas parciales respecto al estado son nulas (<span class="math inline">\(\frac{\partial \sigma}{\partial x} = 0\)</span>), con lo cual por propiedades del cálculo estocástico, el término de corrección de segundo orden del método de Milstein se multiplica por cero y desaparece, reduciéndose de forma exacta al esquema de Euler-Maruyama empleado en esta simulación.</p>
</section>
<section id="sec-resultados-seguridad" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="sec-resultados-seguridad"><span class="header-section-number">4.4.2</span> Resultados de Seguridad Termodinámica</h3>
<p>El algoritmo registra cada evento en el que la temperatura interna del equipo cruza los límites normativos de seguridad (por encima de los <span class="math inline">\(8^\circ\text{C}\)</span> o por debajo de los <span class="math inline">\(2^\circ\text{C}\)</span>). Es importante destacar que en esta trayectoria de prueba, la temperatura de la simulación nunca descendió por debajo del punto de congelación crítico (<span class="math inline">\(0^\circ\text{C}\)</span>) en ninguno de los tres escenarios. El cálculo exacto del riesgo para la trayectoria de control inicial (semilla 13) arrojó los siguientes resultados para cada escenario operativo:</p>
<p><strong>Escenario A (Línea Base):</strong></p>
<ul>
<li><strong><span class="math inline">\(T(t)&gt;8^\circ\text{C}\)</span>:</strong> Se tuvo un total de 40 eventos, sumando un tiempo acumulado de 22.25 horas que representa el 0.25% del año; el primer registro ocurrió en el Día 60.99.</li>
<li><strong><span class="math inline">\(T(t)&lt;2^\circ\text{C}\)</span>:</strong> Se tuvo un total de 13 eventos, sumando un tiempo acumulado de 3.58 horas que representa el 0.04% del año, registrando la primera caída térmica fuera de la norma en el Día 110.25.</li>
<li><strong>Tiempo Total Fuera de Rango:</strong> La suma de las excursiones térmicas resultó en un total de 25.83 horas que representa el 0.29% del año operando fuera del rango normativo.</li>
</ul>
<p><strong>Escenario B (Apego Normativo):</strong></p>
<ul>
<li><strong><span class="math inline">\(T(t)&gt;8^\circ\text{C}\)</span>:</strong> Se observó un incremento notable con un total de 177 eventos, acumulando un total de 121.83 horas que representa el 1.39% del año; debido a la interacción humana, la primera falla crítica se adelantó drásticamente hasta el Día 4.65.</li>
<li><strong><span class="math inline">\(T(t)&lt;2^\circ\text{C}\)</span>:</strong> Ocurrieron únicamente 3 eventos con un tiempo acumulado de 0.83 horas que representa el 0.01% del año, manteniendo su primer registro en el Día 110.25.</li>
<li><strong>Tiempo Total Fuera de Rango:</strong> El equipo operó en condiciones de riesgo durante un total de 122.67 horas que representa el 1.40% del año simulado.</li>
</ul>
<p><strong>Escenario C (Contingencia):</strong></p>
<ul>
<li><strong><span class="math inline">\(T(t)&gt;8^\circ\text{C}\)</span>:</strong> El estrés logístico provocó un total de 435 eventos, alcanzando un tiempo acumulado severo de 475 horas que representa el 5.41% del año; al igual que en el escenario anterior, el primer registro de falla ocurrió rápidamente en el Día 4.65.</li>
<li><strong><span class="math inline">\(T(t)&lt;2^\circ\text{C}\)</span>:</strong> Debido a la saturación de calor por aperturas constantes, no se registró ningún evento de enfriamiento excesivo, manteniéndose un acumulado de 0.00 horas.</li>
<li><strong>Tiempo Total Fuera de Rango:</strong> En este contexto, el equipo sumó un total de 475 horas operando fuera de rango, lo que representa el 5.41% del año.</li>
</ul>
</section>
<section id="análisis-comparativo-de-trayectorias-visión-macro-anual" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="análisis-comparativo-de-trayectorias-visión-macro-anual"><span class="header-section-number">4.4.3</span> Análisis Comparativo de Trayectorias: Visión Macro (Anual)</h3>
<p>A continuación, se presentan las soluciones numéricas completas para un año de simulación bajo los tres escenarios.</p>
<div id="fig-anual-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anual-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="sde_anual_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anual-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.3: Comportamiento térmico anual (Escenario A). Las zonas sombreadas en rojo indican la ocurrencia de los 68 apagones. La trayectoria azul representa la temperatura interna del equipo (la solución numérica de la EDE) la cual se mantiene estable y rara vez rompe la cadena de frío, viéndose afectada únicamente por fallas eléctricas prolongadas, y la trayectoria de color amarillo indica la temperatura ambiente en Tuxtla Gutiérrez, Chiapas.
</figcaption>
</figure>
</div>
<div id="fig-anual-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anual-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="sde_anual_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anual-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.4: Comportamiento térmico anual (Escenario B). La interacción humana controlada engrosa la trayectoria azul, incrementando los picos térmicos debido a las aperturas matutinas y vespertinas.
</figcaption>
</figure>
</div>
<div id="fig-anual-c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anual-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="sde_anual_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anual-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.5: Comportamiento térmico anual (Escenario C). La saturación logística colapsa el control termodinámico; la trayectoria azul se muestra muy oscilatoria, rompiendo continuamente la barrera de los 8°C.
</figcaption>
</figure>
</div>
<p><strong>Interpretación Anual:</strong> La visualización anual demuestra de forma contundente la sensibilidad del sistema a la interacción humana. En el Escenario A, el aislamiento térmico del equipo y el clima de la región son suficientes para mantener la temperatura segura durante los primeros dos meses (enero y febrero), presentando fallas a partir de la época de calor extremo. Conforme avanzamos al Escenario B y C, el volumen de excursiones superiores a <span class="math inline">\(8^\circ\text{C}\)</span> crece agresivamente (pasando de 40 a 435 eventos). Esto prueba que el suministro eléctrico de la CFE, aunque deficiente, no es el destructor principal de la cadena de frío, sino el estrés logístico de las aperturas continuas.</p>
</section>
<section id="análisis-comparativo-de-trayectorias-visión-micro-acercamiento-mensual" class="level3" data-number="4.4.4">
<h3 data-number="4.4.4" class="anchored" data-anchor-id="análisis-comparativo-de-trayectorias-visión-micro-acercamiento-mensual"><span class="header-section-number">4.4.4</span> Análisis Comparativo de Trayectorias: Visión Micro (Acercamiento Mensual)</h3>
<p>Para aislar el comportamiento de la Ecuación Diferencial Estocástica y los impactos térmicos instantáneos (<span class="math inline">\(\gamma_i\)</span>), se realizó un acercamiento al primer mes de la simulación.</p>
<div id="fig-zoom-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-zoom-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="sde_zoom_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-zoom-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.6: Acercamiento del comportamiento de la EDE durante el mes de enero (Escenario A). Se omitió el clima exterior para observar la estabilidad del termostato (5°C), sin la presencia de personal clínico, las únicas perturbaciones observables son curvas suaves de calentamiento pasivo durante los cortes de energía.
</figcaption>
</figure>
</div>
<div id="fig-zoom-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-zoom-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="sde_zoom_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-zoom-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.7: Acercamiento del comportamiento de la EDE durante el mes de enero (Escenario B). Se observan picos verticales (salto térmico) debido a las aperturas de la puerta del refrigerador (triángulos verdes inferiores), seguidos de una recuperación exponencial forzada por el compresor.
</figcaption>
</figure>
</div>
<div id="fig-zoom-c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-zoom-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="sde_zoom_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-zoom-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.8: Acercamiento del comportamiento de la EDE durante el mes de enero (Escenario C). La temperatura rebasa el límite de los 8°C de forma constante debido a la alta frecuencia del proceso de Poisson para viajes de resurtido (mayor cantidad de triángulos verdes).
</figcaption>
</figure>
</div>
<p><strong>Interpretación Mensual:</strong> A nivel mensual, se observa cómo el esquema de Euler-Maruyama resuelve la dinámica de reversión a la media (atracción hacia el termostato de <span class="math inline">\(5^\circ\text{C}\)</span>). Un hallazgo estadístico notable es la coincidencia exacta del primer evento de excursión crítica en los escenarios B y C (ocurrido en el Día 4.65). Esto no es un error numérico, sino la consecuencia directa del modelo acoplado: en el Día 4.65 en el Escenario B y C ocurrió una apertura vespertina con un alto impacto térmico (<span class="math inline">\(\gamma_i\)</span>) que provocó que la temperatura del equipo superara el umbral de los <span class="math inline">\(8^\circ\text{C}\)</span>.</p>
</section>
</section>
<section id="integración-de-la-dinámica-logística-y-mermas" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="integración-de-la-dinámica-logística-y-mermas"><span class="header-section-number">4.5</span> Integración de la Dinámica Logística y Mermas</h2>
<p>Para pasar de una pérdida de viabilidad teórica a la pérdida de vacunas, acomodamos la simulación a un modelo de inventario dinámico (<span class="math inline">\(I(t)\)</span>), donde <span class="math inline">\(t\)</span> representa el tiempo cada 5 minutos. El algoritmo avanza en el tiempo y evalúa tres reglas operativas clave para la logística:</p>
<ol type="1">
<li><strong>Consumo Logístico:</strong> Dependiendo del escenario como se vio en la <a href="Estudio_de_caso.html#sec-dinamica-inventario" class="quarto-xref"><span>Sección 3.11</span></a>, el volumen de vacunas se descuenta del inventario. Para el Escenario A (Línea Base), el consumo es cero. Para el Escenario B (Apego Normativo), se extrae una cantidad diaria fija a las 8:00 AM que varía según el mes (ej. mayor demanda en octubre por la campaña de Influenza). Para el Escenario C (Contingencia), el consumo acelera y se acopla de manera dinámica a los eventos de resurtido a lo largo de la jornada.</li>
<li><strong>Inercia Térmica y Daño Farmacológico:</strong> La temperatura <span class="math inline">\(T(t)\)</span> calculada por la EDE corresponde al aire interno del equipo. Sin embargo, el biológico líquido dentro de los frascos de vidrio posee inercia térmica. Para modelar este retardo físico, el algoritmo aplica un filtro de tolerancia de 30 minutos: la ecuación de Arrhenius solo entra en vigor si el aire permanece por encima de los 8°C de manera ininterrumpida durante 6 iteraciones continuas. Cumplida esta condición, se extrae la fracción de pérdida y se multiplica por el inventario actual en ese instante de tiempo, sumando el resultado al vector de dosis destruidas.</li>
<li><strong>Reabastecimiento Automático:</strong> Si el inventario cae por debajo del punto de reorden de 1000 dosis (el 20% de su capacidad máxima), se simula la llegada de la ruta jurisdiccional que llena el equipo hasta su capacidad máxima de 5000 dosis, registrando el ingreso en la sumatoria anual para calcular el porcentaje de pérdida final.</li>
</ol>
<section id="resultados-del-impacto-logístico" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="resultados-del-impacto-logístico"><span class="header-section-number">4.5.1</span> Resultados del Impacto Logístico</h3>
<p>Al finalizar el año de simulación para la trayectoria de control (semilla 13), la interacción entre la EDE, el filtro de inercia de 30 minutos y el modelo de inventario arrojó los siguientes resultados totales de pérdida física:</p>
<p><strong>Escenario A (Línea Base):</strong> Dado que no existe consumo operativo, el equipo operó de manera estática, registrando un ingreso total y único de 5000 dosis al inicio del año. De este volumen inmovilizado, los cortes eléctricos de la red externa lograron destruir un total de 108 dosis, lo que representa un porcentaje de pérdida anual del 2.16%.</p>
<p><strong>Escenario B (Apego Normativo):</strong> La dinámica de vacunación diaria generó una sana rotación del inventario, registrando un ingreso total de 25373 dosis a lo largo del año. Gracias a que las aperturas de la puerta son moderadas, el control térmico se mantuvo estable y únicamente se destruyeron 414 dosis, logrando el porcentaje de pérdida anual más bajo de los tres escenarios con apenas un 1.63%.</p>
<p><strong>Escenario C (Contingencia):</strong> La contingencia obligó a realizar viajes masivos de reabastecimiento, elevando drásticamente el flujo anual a 77843 dosis. La coincidencia del alto volumen de vacunas almacenadas con el colapso térmico, provocado por la saturación de aperturas, provocó una destrucción severa de 2395 dosis, alcanzando el porcentaje de pérdida anual más alto con un 3.08%.</p>
</section>
<section id="análisis-comparativo-del-inventario-y-riesgo-materializado" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="análisis-comparativo-del-inventario-y-riesgo-materializado"><span class="header-section-number">4.5.2</span> Análisis Comparativo del Inventario y Riesgo Materializado</h3>
<p>Para visualizar cómo interactúa el consumo operativo con los momentos exactos de falla termodinámica, se generaron gráficas de doble eje para los tres escenarios en estudio.</p>
<div id="fig-logistica-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-logistica-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inventario_vs_mermas_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logistica-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.9: Dinámica logística anual (Escenario A). La trayectoria continua de color azul (eje izquierdo) representa el nivel de inventario activo, el cual se mantiene como una línea recta casi todo el año debido a la ausencia de extracciones. La trayectoria escalonada de color rojo (eje derecho) representa el crecimiento acumulado de las dosis perdidas, observando que los saltos o daños coinciden exclusivamente a cuando se rompe la cadena de frío de manera prolongada.
</figcaption>
</figure>
</div>
<div id="fig-logistica-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-logistica-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inventario_vs_mermas_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logistica-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.10: Dinámica logística anual (Escenario B). La trayectoria azul muestra el patrón típico de “diente de sierra” generado por la extracción diaria a las 8:00 AM y los resurtidos verticales al tocar el punto de reorden. La trayectoria roja de mermas acumuladas crece de forma espaciada y moderada.
</figcaption>
</figure>
</div>
<div id="fig-logistica-c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-logistica-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="inventario_vs_mermas_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logistica-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.11: Dinámica logística anual (Escenario C). La trayectoria azul evidencia un consumo caótico por la contingencia, obligando a múltiples resurtidos por semana. En consecuencia, la trayectoria roja se dispara agresivamente en forma exponencial.
</figcaption>
</figure>
</div>
<p><strong>Interpretación de la Dinámica Logística:</strong></p>
<p>La visualización del inventario revela una aparente contradicción de riesgo. Como se vio anteriormente en la <a href="#sec-resultados-seguridad" class="quarto-xref"><span>Sección 4.4.2</span></a>, el Escenario A tuvo menos excursiones térmicas que el Escenario B; sin embargo, su porcentaje de pérdida logística fue mayor (2.16% frente a 1.63%). Esto se debe al efecto protector de la rotación: en la Línea Base, las mismas 5000 dosis permanecen estancadas absorbiendo el impacto de cada corte eléctrico del año; en cambio, el Apego Normativo salva las dosis al aplicarlas en pacientes antes de que ocurran los apagones.</p>
<p>No obstante, cuando el ritmo logístico sale de control (Escenario C), esta protección colapsa. El exceso de aperturas no solo rompe la cadena de frío, sino que al estar el equipo constantemente lleno, cada excursión térmica encuentra miles de vacunas vulnerables al mismo tiempo, multiplicando el daño absoluto a 2395 dosis, es decir, un 3.08% de pérdida anual.</p>
</section>
</section>
<section id="estructura-de-la-simulación-de-montecarlo" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="estructura-de-la-simulación-de-montecarlo"><span class="header-section-number">4.6</span> Estructura de la Simulación de Montecarlo</h2>
<p>Con el fin de obtener validez científica y no depender del resultado de un solo escenario al azar, el algoritmo completo se incluyo dentro de una función para simular años completos de manera repetitiva. Para optimizar drásticamente la velocidad de ejecución y evitar el desbordamiento de la memoria RAM del sistema durante el análisis masivo, el programa se diseñó para extraer y almacenar únicamente métricas estadísticas clave en cada iteración, omitiendo la conservación de los arreglos gigantes de datos por cada año evaluado.</p>
<p>Entre las métricas extraídas de esta función se incluyen:</p>
<ul>
<li><strong>Termodinámica:</strong> Horas acumuladas y conteo de las rupturas de la cadena de frío (<span class="math inline">\(T(t)&gt;8^\circ\text{C}\)</span> y <span class="math inline">\(T(t)&lt;2^\circ\text{C}\)</span>), así como la vigilancia del riesgo crítico de congelación (<span class="math inline">\(T(t)&lt;0^\circ\text{C}\)</span>).</li>
<li><strong>Logística y Riesgo:</strong> El día exacto en que ocurrió la primera falla crítica, el total de dosis perdidas, el porcentaje anual de pérdida y la merma por mes para evaluar la estacionalidad del riesgo.</li>
</ul>
<p>Esta función se ejecuta dentro de un bucle de Montecarlo con <strong>5,000 simulaciones independientes</strong>, asignando en cada paso una semilla de aleatoriedad indexada para garantizar la reproducibilidad del experimento. Al correr los 5,000 años simulados, el algoritmo elimina las variaciones extremas de los casos individuales y permite que actúe la <strong>Ley de los Grandes Números</strong> <span class="citation" data-cites="ross2018first">(<a href="references.html#ref-ross2018first" role="doc-biblioref">Ross 2018</a>)</span>. Esto provoca que las métricas de control se estabilicen firmemente, permitiendo extraer promedios poblacionales realistas sobre el comportamiento del equipo institucional bajo cada uno de los tres escenarios operativos evaluados.</p>
</section>
<section id="resultados-estadísticos-y-análisis-de-riesgo" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="resultados-estadísticos-y-análisis-de-riesgo"><span class="header-section-number">4.7</span> Resultados Estadísticos y Análisis de Riesgo</h2>
<p>Una vez completadas las 5,000 simulaciones de Montecarlo, procedemos a extraer las métricas operativas y termodinámicas de todos los años simulados. La simulación masiva de trayectorias revela el verdadero comportamiento del sistema a largo plazo, eliminando las variaciones extremas de un solo año al azar.</p>
<p>A continuación, se presenta la tabla comparativa con los promedios poblacionales empíricos, seguida del análisis descriptivo de dispersión e intervalos de confianza para cada escenario.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Métrica (Promedio Anual)</th>
<th style="text-align: center;">Escenario A (Línea Base)</th>
<th style="text-align: center;">Escenario B (Apego Normativo)</th>
<th style="text-align: center;">Escenario C (Contingencia)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Perturbaciones Externas</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Apagones de la CFE</td>
<td style="text-align: center;">64.3</td>
<td style="text-align: center;">64.3</td>
<td style="text-align: center;">64.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aperturas de Puerta</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">499</td>
<td style="text-align: center;">998</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Riesgo Termodinámico</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(T(t) &gt; 8^\circ\text{C}\)</span></td>
<td style="text-align: center;">26.4 eventos</td>
<td style="text-align: center;">134.6 eventos</td>
<td style="text-align: center;">419.7 eventos</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(T(t) &lt; 2^\circ\text{C}\)</span></td>
<td style="text-align: center;">25.2 eventos</td>
<td style="text-align: center;">12.5 eventos</td>
<td style="text-align: center;">9.0 eventos</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(T(t) &lt; 0^\circ\text{C}\)</span></td>
<td style="text-align: center;">0 eventos</td>
<td style="text-align: center;">0 eventos</td>
<td style="text-align: center;">0 eventos</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tiempo Fuera de Rango Normativo</td>
<td style="text-align: center;">24.4 horas (0.28%)</td>
<td style="text-align: center;">95.6 horas (1.09%)</td>
<td style="text-align: center;">420.6 horas (4.79%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Impacto Logístico (Mermas)</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Dosis Perdidas (Volumen)</td>
<td style="text-align: center;">61 dosis</td>
<td style="text-align: center;">343 dosis</td>
<td style="text-align: center;">1,905 dosis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pérdida Relativa (%)</td>
<td style="text-align: center;">1.21%</td>
<td style="text-align: center;">1.36%</td>
<td style="text-align: center;">2.57%</td>
</tr>
</tbody>
</table>
<section id="riesgo-operativo-y-termodinámico-empírico" class="level3" data-number="4.7.1">
<h3 data-number="4.7.1" class="anchored" data-anchor-id="riesgo-operativo-y-termodinámico-empírico"><span class="header-section-number">4.7.1</span> Riesgo Operativo y Termodinámico Empírico</h3>
<p><strong>Escenario A (Línea Base):</strong> La simulación de Montecarlo estabilizó el riesgo externo en un promedio de 64.3 apagones anuales. Al no existir interacción humana (cero aperturas), el riesgo recae puramente en la termodinámica pasiva del equipo. Se registró un promedio de 26.4 rupturas de la cadena de frío anuales por encima de los <span class="math inline">\(8^\circ\text{C}\)</span> (acumulando 12.6 horas) y 25.2 rupturas por debajo de los <span class="math inline">\(2^\circ\text{C}\)</span> (acumulando 11.8 horas). Es necesario destacar que la inercia térmica protegió al equipo de la congelación profunda, manteniendo el riesgo por debajo de los <span class="math inline">\(0^\circ\text{C}\)</span> estrictamente en cero. En el ámbito logístico, esta exposición pasiva provocó una destrucción promedio de 61 dosis (1.21% de pérdida anual). Sin embargo, el intervalo de confianza del 95% resulta muy amplio, oscilando entre apenas 2 y hasta 179 dosis destruidas al año, lo que sugiere una alta volatilidad ante apagones inusualmente largos.</p>
<p><strong>Escenario B (Apego Normativo):</strong> Al introducir la interacción humana con un promedio de 499 aperturas anuales, el riesgo termodinámico aumentó significativamente. Los eventos donde <span class="math inline">\(T(t) &gt; 8^\circ\text{C}\)</span> aumentaron a un promedio de 134.6, acumulando 90 horas de riesgo térmico (1.02% del año), en cambio, los eventos por debajo de los <span class="math inline">\(2^\circ\text{C}\)</span> disminuyeron a un promedio de 12.5, acumulando 5.6 horas (0.06% del año). Adicionalmente, el primer registro de falla crítica se adelantó drásticamente: de promediar en el Día 38 (Escenario A) a ocurrir en el Día 8. Este nivel de estrés aumentó las pérdidas a un promedio de 343 dosis anuales (1.36% de pérdida anual), con un intervalo de confianza del 95% que advierte escenarios de riesgo donde un equipo normado puede perder entre 166 y hasta 573 dosis en un solo año.</p>
<p><strong>Escenario C (Contingencia):</strong> La saturación logística colapsa por completo la cadena de frío. Con casi 1,000 aperturas anuales (998), el equipo sufre 419.7 rupturas de la cadena de frío anuales por encima de los <span class="math inline">\(8^\circ\text{C}\)</span> en promedio (acumulando 416.5 horas) y 9 rupturas por debajo de los <span class="math inline">\(2^\circ\text{C}\)</span> (acumulando 4.1 horas), acumulando un valor crítico total de 420.6 horas (4.79% del año) operando fuera de rango. Bajo este escenario de estrés extremo, el primer cruce fuera de la norma ocurre en promedio apenas en el Día 3 de operación. El impacto en el inventario es devastador: se pierden en promedio 1,905 dosis por año (2.57% de pérdida anual), con un intervalo de confianza del 95% que va de 1348 hasta las 2,521 dosis destruidas.</p>
<p><strong>Interpretación Comparativa del Modelo:</strong></p>
<p>Aplicando la <strong>Ley de los Grandes Números</strong>, a través de las 5,000 simulaciones se resolvió la contradicción de riesgo observada en la trayectoria de prueba inicial. Aunque en años individuales aislados la inmovilidad del inventario (Escenario A) puede resultar en una mayor pérdida relativa frente al consumo normativo (Escenario B) debido al efecto protector de la rotación de vacunas, el promedio poblacional a largo plazo demuestra lo contrario. A la larga, el volumen masivo de rupturas de la cadena de frío provocadas por las 499 aperturas del Escenario B sobrepasa cualquier beneficio de rotación, situando su pérdida promedio (1.36%) por encima del aislamiento absoluto (1.21%). Además, se confirma que el colapso operativo (Escenario C) no es un riesgo lineal, sino exponencial: duplicar las aperturas de puerta no duplicó las pérdidas, sino que las multiplicó por más de cinco veces (de 343 a 1,905 dosis), evidenciando la fragilidad termodinámica de los equipos frente a la saturación clínica.</p>
</section>
<section id="análisis-de-trayectorias" class="level3" data-number="4.7.2">
<h3 data-number="4.7.2" class="anchored" data-anchor-id="análisis-de-trayectorias"><span class="header-section-number">4.7.2</span> Análisis de Trayectorias</h3>
<p>La tabla anterior revela que los intervalos de confianza del 95% para la pérdida de biológicos son muy amplios en todos los escenarios operativos. Para comprender visualmente la causa de esta dispersión, se extrajo una submuestra aleatoria de 30 trayectorias (30 años simulados distintos) para cada escenario.</p>
<p>El comportamiento de los daños acumulados demuestra que el riesgo no es lineal. La tendencia de las dosis perdidas a lo largo de los 366 días depende estrictamente de la coincidencia temporal exacta entre la ocurrencia de un apagón prolongado de la CFE y el nivel de saturación de vacunas almacenadas en ese día específico.</p>
<div id="fig-abanico-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-abanico-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="abanico_riesgo_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-abanico-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.12: 30 trayectorias anuales aleatorias (Escenario A). Las trayectorias se mantienen planas (cero pérdidas) durante largos periodos de tiempo. Cuando ocurre un apagón que supera la inercia térmica, la trayectoria sube drásticamente (escalón vertical). La gran separación vertical entre las líneas al final del año (Día 366) explica visualmente la alta varianza del modelo.
</figcaption>
</figure>
</div>
<div id="fig-abanico-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-abanico-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="abanico_riesgo_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-abanico-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.13: 30 trayectorias anuales aleatorias (Escenario B). El estrés introducido por las aperturas matutinas y vespertinas aumenta la acumulación de daños. En lugar de escalones aislados, las trayectorias muestran un crecimiento en forma de escalera continua a lo largo de todo el año, evidenciando una constante ruptura de la cadena de frío.
</figcaption>
</figure>
</div>
<div id="fig-abanico-c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-abanico-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="abanico_riesgo_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-abanico-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.14: 30 trayectorias anuales aleatorias (Escenario C). La saturación logística colapsa la termodinámica del sistema. Las trayectorias abandonan el comportamiento escalonado y adoptan una pendiente positiva continua casi recta. Todas las líneas se disparan uniformemente hacia arriba, superando rápidamente el umbral de las 1,000 dosis destruidas.
</figcaption>
</figure>
</div>
<p><strong>Interpretación Comparativa de las Trayectorias:</strong></p>
<p>Al observar el comportamiento de las 30 trayectorias conjuntas, se comprueba la hipótesis de fragilidad de la red de frío. En el Escenario A, el aislamiento absoluto permite que existan “años afortunados” donde el equipo apenas pierde unas cuantas dosis, pero basta un solo año con un apagón crítico prolongado para que la pérdida escale drásticamente (como se observa en la línea superior en la <a href="#fig-abanico-a" class="quarto-xref">Figura&nbsp;<span>4.12</span></a> que cruza las 200 dosis).</p>
<p>Por el contrario, el Escenario C demuestra que la contingencia operativa elimina el factor “suerte”. La densidad y homogeneidad de las trayectorias confirman que, bajo estrés logístico masivo, el colapso del biológico está garantizado independientemente de si el clima de ese año fue favorable o si hubo menos apagones. La saturación de aperturas domina por completo al sistema, provocando una destrucción acelerada, continua e inevitable.</p>
</section>
<section id="estacionalidad-del-riesgo-operativo" class="level3" data-number="4.7.3">
<h3 data-number="4.7.3" class="anchored" data-anchor-id="estacionalidad-del-riesgo-operativo"><span class="header-section-number">4.7.3</span> Estacionalidad del Riesgo Operativo</h3>
<p>Al desglosar las pérdidas de dosis de forma mensual, los datos revelan el verdadero comportamiento del riesgo termodinámico a lo largo del año. Para evaluar esta métrica de forma rigurosa, se analizaron dos estimadores de centralidad: el promedio mensual (que es sensible a los años con apagones catastróficos) y la mediana mensual (estadísticamente más robusta porque representa el escenario más probable, aislando las fluctuaciones extremas).</p>
<p>Inicialmente, desde un punto de vista puramente climático, se podría suponer que los meses de calor extremo en Tuxtla Gutiérrez (abril y mayo) presentarían la mayor cantidad de vacunas perdidas debido al estrés térmico ambiental sobre el equipo. No obstante, las 5,000 simulaciones de Montecarlo demuestran que la interacción humana modifica por completo este patrón natural.</p>
<p><strong>Escenario A (Línea Base):</strong></p>
<div id="layout-barras-a" class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-promedio-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-promedio-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="barras_estacionales_promedio_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-promedio-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.15: Pérdida promedio mensual (Escenario A). Se observa una pérdida uniforme de alrededor de 5 dosis mensuales, con un ligero pico en mayo debido a las fallas eléctricas por estrés térmico.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mediana-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediana-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="barras_estacionales_mediana_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediana-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.16: Pérdida mediana mensual (Escenario A). La mediana se mantiene estrictamente en cero durante los 12 meses del año, demostrando que en al menos el 50% de los escenarios climáticos normales no se pierde ni una sola vacuna al mes.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Escenario B (Apego Normativo):</strong></p>
<div id="layout-barras-b" class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-promedio-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-promedio-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="barras_estacionales_promedio_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-promedio-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.17: Pérdida promedio mensual (Escenario B). El estrés logístico aumenta significativamente las pérdidas. El mes de enero alcanza casi 40 dosis perdidas, seguido por un pico secundario en agosto durante la temporada de tormentas.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mediana-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediana-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="barras_estacionales_mediana_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediana-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.18: Pérdida mediana mensual (Escenario B). A diferencia del Escenario A, la mediana ya no es cero. Enero y agosto se consolidan como los meses de mayor riesgo operativo esperado.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Escenario C (Contingencia):</strong></p>
<div id="layout-barras-c" class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-promedio-c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-promedio-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="barras_estacionales_promedio_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-promedio-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.19: Pérdida promedio mensual (Escenario C). La saturación logística domina el sistema, superando las 150 dosis mensuales de forma casi homogénea a lo largo del año.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mediana-c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediana-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="barras_estacionales_mediana_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediana-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.20: Pérdida mediana mensual (Escenario C). El colapso se confirma. Julio destaca ligeramente como el mes más crítico, superando las 160 dosis perdidas como escenario más probable.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Interpretación de la Estacionalidad:</strong></p>
<p>El análisis estacional confirma que <strong>el estrés operativo domina por completo al factor climático.</strong> En el Escenario A, la <a href="#fig-mediana-a" class="quarto-xref">Figura&nbsp;<span>4.16</span></a> demuestra que la infraestructura termoaislante del equipo Haier HBC-150 es lo suficientemente robusta para sobrevivir a la intemperie chiapaneca sin sufrir daños (mediana igual a cero en todos los meses). Las pérdidas residuales observadas en el promedio del Escenario A son producto exclusivo de la cola de la distribución (años atípicamente catastróficos).</p>
<p>Sin embargo, al introducir la interacción humana, el patrón climático desaparece. En el Escenario B, la vulnerabilidad ya no recae en la primavera, sino que se desplaza hacia enero y agosto, coincidiendo con las épocas donde el volumen del inventario interactúa de manera letal con las perturbaciones eléctricas. Finalmente, en el Escenario C, la contingencia operativa nivela el riesgo: el equipo pierde su capacidad de recuperación térmica provocando que todos los meses del año (sin importar si es invierno o verano) resulten devastadores para la viabilidad de las vacunas, consolidando la destrucción sistemática del inventario activo.</p>
</section>
</section>
<section id="de-aqui" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> DE AQUI</h1>
<section id="distribución-del-riesgo-operativo" class="level3" data-number="5.0.1">
<h3 data-number="5.0.1" class="anchored" data-anchor-id="distribución-del-riesgo-operativo"><span class="header-section-number">5.0.1</span> Distribución del Riesgo Operativo</h3>
<p>Para estandarizar el nivel de riesgo sin importar la escala de la unidad médica, las dosis destruidas se transformaron en porcentajes de pérdida relativa respecto al volumen total de vacunas manejadas por el equipo en cada año simulado. La visualización de la frecuencia de estas pérdidas a lo largo de las 5,000 iteraciones de Montecarlo nos permite analizar la forma de la distribución del riesgo para cada escenario operativo.</p>
<div id="fig-hist-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="histograma_porcentajes_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.1: Histograma del porcentaje de vacunas perdidas anualmente (Escenario A)[cite: 13]. La distribución presenta una fuerte asimetría positiva (una cola larga estirada hacia la derecha). Esto indica que, aunque la concentración principal de los datos sugiere pérdidas bajas (mediana del 1.01%), existen años atípicamente catastróficos que arrastran el promedio general hacia arriba (1.21%). Las líneas rojas punteadas delimitan el intervalo empírico del 95%, mostrando la alta dispersión hacia escenarios extremos.
</figcaption>
</figure>
</div>
<div id="fig-hist-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="histograma_porcentajes_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.2: Histograma del porcentaje de vacunas perdidas anualmente (Escenario B)[cite: 14]. Al introducir el estrés logístico normativo, la distribución completa se desplaza hacia la derecha, incrementando tanto la mediana (1.32%) como la media (1.36%). Aunque la asimetría disminuye ligeramente en comparación con la Línea Base, la cola derecha sigue advirtiendo de escenarios de riesgo donde la pérdida relativa supera el 2.20%.
</figcaption>
</figure>
</div>
<div id="fig-hist-c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="histograma_porcentajes_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.3: Histograma del porcentaje de vacunas perdidas anualmente (Escenario C)[cite: 15]. La contingencia extrema transforma drásticamente la forma de la distribución, volviéndola visualmente simétrica (similar a una campana de Gauss). La media (2.57%) y la mediana (2.56%) prácticamente se igualan, consolidando un nivel de destrucción base sumamente alto y un intervalo de confianza del 95% altamente concentrado.
</figcaption>
</figure>
</div>
<p><strong>Interpretación de las Distribuciones:</strong></p>
<p>La visualización de los histogramas demuestra que la dinámica del riesgo evoluciona conforme aumenta la interacción humana. En el Escenario A y B, la clara separación entre la media (línea azul) y la mediana (línea verde) evidencia que los datos están sesgados; este comportamiento asimétrico es típico de los sistemas de riesgo operativo pasivos, donde los daños dependen de fallas externas intermitentes y severas (como los apagones prolongados de la CFE).</p>
<p>Sin embargo, en el Escenario C, la distribución adopta una forma simétrica. Esto ocurre gracias al Teorema del Límite Central: la altísima frecuencia de aperturas de puerta (casi 1,000 al año) se convierte en el factor dominante del sistema, “suavizando” el impacto de los apagones aislados y garantizando una tasa de pérdida constante y predeciblemente alta. La asimetría visual observada en los primeros dos escenarios sugiere fuertemente que las distribuciones no siguen un comportamiento normal, lo cual requiere una comprobación matemática estricta antes de realizar inferencias poblacionales definitivas.</p>
</section>
</section>
<section id="hasta-aqui" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> HASTA AQUI</h1>
<p>#imagenes finales sin interpretacion momentanea:</p>
<div id="fig-boxplot-final-escenario-A" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-final-escenario-A-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="boxplot_angosto_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-final-escenario-A-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.1: gráfica de caja
</figcaption>
</figure>
</div>
<div id="fig-boxplot-final-escenario-B" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-final-escenario-B-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="boxplot_angosto_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-final-escenario-B-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.2: gráfica de caja
</figcaption>
</figure>
</div>
<div id="fig-boxplot-final-escenario-C" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-final-escenario-C-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="boxplot_angosto_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-final-escenario-C-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.3: gráfica de caja
</figcaption>
</figure>
</div>
<div id="fig-histograma-bootstrap-escenario-A" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-histograma-bootstrap-escenario-A-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="histograma_bootstrap_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-histograma-bootstrap-escenario-A-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.4: histograma Bootstrap
</figcaption>
</figure>
</div>
<div id="fig-histograma-bootstrap-escenario-B" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-histograma-bootstrap-escenario-B-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="histograma_bootstrap_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-histograma-bootstrap-escenario-B-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.5: histograma Bootstrap
</figcaption>
</figure>
</div>
<div id="fig-histograma-bootstrap-escenario-C" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-histograma-bootstrap-escenario-C-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="histograma_bootstrap_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-histograma-bootstrap-escenario-C-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.6: histograma Bootstrap
</figcaption>
</figure>
</div>
<div id="fig-boxplot-bootstrap-escenario-A" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-bootstrap-escenario-A-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="boxplot_bootstrap_escenario_A.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-bootstrap-escenario-A-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.7: Grafica de caja Boostrap
</figcaption>
</figure>
</div>
<div id="fig-boxplot-bootstrap-escenario-B" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-bootstrap-escenario-B-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="boxplot_bootstrap_escenario_B.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-bootstrap-escenario-B-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.8: Grafica de caja Boostrap
</figcaption>
</figure>
</div>
<div id="fig-boxplot-bootstrap-escenario-C" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-bootstrap-escenario-C-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="boxplot_bootstrap_escenario_C.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-bootstrap-escenario-C-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.9: Grafica de caja Boostrap
</figcaption>
</figure>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Perez2026EscenarioA" class="csl-entry" role="listitem">
Pérez, C. 2026a. <span>«Simulación y Análisis de Riesgo en la Red de Frío para Vacunas - Escenario A (Línea Base): Código Fuente en Python»</span>. <a href="https://github.com/Crisperez517/Tesis/blob/dd475b5346eeefe92d64385f7e8993b8f93b66b5/TESIS_Simulaci%C3%B3n_Escenario_A.ipynb">https://github.com/Crisperez517/Tesis/blob/dd475b5346eeefe92d64385f7e8993b8f93b66b5/TESIS_Simulaci%C3%B3n_Escenario_A.ipynb</a>.
</div>
<div id="ref-Perez2026EscenarioB" class="csl-entry" role="listitem">
———. 2026b. <span>«Simulación y Análisis de Riesgo en la Red de Frío para Vacunas - Escenario B (Apego Normativo): Código Fuente en Python»</span>. <a href="https://github.com/Crisperez517/Tesis/blob/dd475b5346eeefe92d64385f7e8993b8f93b66b5/TESIS_Simulaci%C3%B3n_Escenario_B.ipynb">https://github.com/Crisperez517/Tesis/blob/dd475b5346eeefe92d64385f7e8993b8f93b66b5/TESIS_Simulaci%C3%B3n_Escenario_B.ipynb</a>.
</div>
<div id="ref-Perez2026EscenarioC" class="csl-entry" role="listitem">
———. 2026c. <span>«Simulación y Análisis de Riesgo en la Red de Frío para Vacunas - Escenario C (Contingencia Operativa): Código Fuente en Python»</span>. <a href="https://github.com/Crisperez517/Tesis/blob/dd475b5346eeefe92d64385f7e8993b8f93b66b5/TESIS_Simulaci%C3%B3n_Escenario_C.ipynb">https://github.com/Crisperez517/Tesis/blob/dd475b5346eeefe92d64385f7e8993b8f93b66b5/TESIS_Simulaci%C3%B3n_Escenario_C.ipynb</a>.
</div>
<div id="ref-ross2018first" class="csl-entry" role="listitem">
Ross, Sheldon M. 2018. <em>A First Course in Probability</em>. 10th ed. Pearson.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Estudio_de_caso.html" class="pagination-link" aria-label="Estudio de Caso: Calibración Termodinámica, Eléctrica y Cinética de Degradación">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudio de Caso: Calibración Termodinámica, Eléctrica y Cinética de Degradación</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./conclusiones.html" class="pagination-link" aria-label="Conclusiones y Trabajo Futuro">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conclusiones y Trabajo Futuro</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>